const allData = [
  [` autosave `, ` 个自动保存 `],
  [` Copy link`, ` 复制链接`],
  [` device.`, ` 设备上下载 Figma Mirror。`],
  [` follower`, ` 关注者`],
  [` following`, ` 正在关注`],
  [` for unlimited design files, projects, and shared team libraries.`, `用于无限的设计文件、项目和共享的团队库。`],
  [` Get embed code`, ` 获取嵌入代码`],
  [` in the main menu.`, `（在主菜单里面）跳转到那边。`],
  [` Learn more`, ` 了解更多`],
  [` learn more`, ` 了解更多`],
  [` of 1 project used`, ` / 1 个项目被使用`],
  [` of 3 Figma design files used`, ` / 3 个 Figma 设计文件被使用`],
  [` on `, ` 发布于 `],
  [` or `, ` 或 `],
  [` projects`, ` 项目`],
  [` Sign up`, ` 注册`],
  [` started following you`, ` 关注了你`],
  [` team libraries`, ` 团队组件库`],
  [` to create your own plugin and manage any plugins currently in development.`, ` 来创建你自己的插件，以及管理在开发中的插件`],
  [` to create your own plugin.`, ` 创建你自己的插件`],
  [` version history`, ` 版本历史`],
  [` viewers`, `查看者`],
  [` when you choose the annual plan.`, ` 当你选择年付计划时。`],
  [`. Please assign a new owner from the team members list before leaving this team.`, `“的创建者。在离开这个团队之前，请从团队成员列表中指定一个新的创建者。`],
  [`.`, `。`],
  [`· Edited `, `· 编辑于 `],
  [`’ project. Notifications are encrypted.`, `”项目中的文件发表评论时，就会收到通知。通知是加密的。`],
  [`(best for 9+ seats)`, `（建议 9 个人以上）`],
  [`(missing)`, `(已丢失)`],
  [`(threads you're involved in)`, `（我参与的主题）`],
  [`(You)`, `(你)`],
  [`/mo.`, `/月`],
  [`←  Everything in Professional, plus`, `←  专业版的所有功能，加上`],
  [`↓ Duplicate`, `↓ 创建副本`],
  [`↓ Install`, `↓ 安装`],
  [`↩ Enter`, `↩ 回车`],
  [`✓  Centralized teams`, `✓  中心化的团队`],
  [`✓  Custom file/user permissions`, `✓  自定义文件/用户权限`],
  [`✓  Design System Analytics`, `✓  设计系统分析`],
  [`✓  Figma auto-saves your work`, `✓ Figma 自动保存你的工作`],
  [`✓  Installed`, `✓ 已安装`],
  [`✓  Invite-only private projects`, `✓  仅限受邀的私人项目`],
  [`✓  Org-wide team libraries`, `✓  全组织的团队组件库`],
  [`✓  Private plugins`, `✓  私有插件`],
  [`✓  Sharable team libraries`, `✓  可共享的团队组件库`],
  [`✓  Shared fonts`, `✓  共享字体`],
  [`✓  SSO and advanced security`, `✓  SSO 和高级安全`],
  [`✓  Unlimited projects`, `✓  无限制的项目`],
  [`✓  Unlimited version history`, `✓  无限制的版本历史`],
  [`1 day ago`, `1 天前`],
  [`1 hour ago`, `1 小时前`],
  [`1 year ago`, `1 年前`],
  [`10 days ago`, `10 天前`],
  [`10 hours ago`, `10 小时前`],
  [`10 months ago`, `10 个月前`],
  [`100% – Display at full size`, `100% - 以完整尺寸显示`],
  [`11 days ago`, `11 天前`],
  [`11 hours ago`, `11 小时前`],
  [`11 months ago`, `11 个月前`],
  [`12 days ago`, `12 天前`],
  [`12 hours ago`, `12 小时前`],
  [`13 days ago`, `13 天前`],
  [`13 hours ago`, `13 小时前`],
  [`14 days ago`, `14 天前`],
  [`14 hours ago`, `14 小时前`],
  [`15 days ago`, `15 天前`],
  [`15 hours ago`, `15 小时前`],
  [`16 days ago`, `16 天前`],
  [`16 hours ago`, `16 小时前`],
  [`17 days ago`, `17 天前`],
  [`17 hours ago`, `17 小时前`],
  [`18 days ago`, `18 天前`],
  [`18 hours ago`, `18 小时前`],
  [`19 days ago`, `19 天前`],
  [`19 hours ago`, `19 小时前`],
  [`2 days ago`, `2 天前`],
  [`2 hours ago`, `2 小时前`],
  [`2 months ago`, `2 个月前`],
  [`20 days ago`, `20 天前`],
  [`20 hours ago`, `20 小时前`],
  [`21 days ago`, `21 天前`],
  [`21 hours ago`, `21 小时前`],
  [`22 days ago`, `22 天前`],
  [`22 hours ago`, `22 小时前`],
  [`23 days ago`, `23 天前`],
  [`23 hours ago`, `23 小时前`],
  [`24 days ago`, `24 天前`],
  [`25 days ago`, `25 天前`],
  [`26 days ago`, `26 天前`],
  [`27 days ago`, `27 天前`],
  [`28 days ago`, `28 天前`],
  [`29 days ago`, `29 天前`],
  [`3 days ago`, `3 天前`],
  [`3 hours ago`, `3 小时前`],
  [`3 months ago`, `3 个月前`],
  [`3 projects`, `3 个项目`],
  [`30-day version history`, `30 天版本历史`],
  [`4 days ago`, `4 天前`],
  [`4 hours ago`, `4 小时前`],
  [`4 months ago`, `4 个月前`],
  [`5 days ago`, `5 天前`],
  [`5 hours ago`, `5 小时前`],
  [`5 months ago`, `5 个月前`],
  [`6 days ago`, `6 天前`],
  [`6 hours ago`, `6 小时前`],
  [`6 months ago`, `6 个月前`],
  [`7 days ago`, `7 天前`],
  [`7 hours ago`, `7 小时前`],
  [`7 months ago`, `7 个月前`],
  [`8 days ago`, `8 天前`],
  [`8 hours ago`, `8 小时前`],
  [`8 months ago`, `8 个月前`],
  [`9 days ago`, `9 天前`],
  [`9 hours ago`, `9 小时前`],
  [`9 months ago`, `9 个月前`],
  [`A bi-weekly email of noteworthy files, plugins & creators`, `每两周一次的电子邮件，值得注意的文件，插件和创作者`],
  [`A deleted component is still published in the Team Library`, `被删除的组件仍在团队库中发布。`],
  [`a new look`, `更新啦~`],
  [`A weekly summary of Community engagement with my files, plugins, and profile`, `社区参与我的文件、插件和档案的每周总结`],
  [`about comments in Community`, `关于社区中的评论`],
  [`About us`, `关于我们`],
  [`Accept`, `接受`],
  [`Account settings`, `账号设置`],
  [`Account`, `账号`],
  [`Action`, `动作`],
  [`actions`, `滚动动作`],
  [`Activity from other users`, `其他用户的活动`],
  [`Add a description`, `添加简介`],
  [`Add a location`, `添加位置`],
  [`Add a project to your favorites to see it here`, `添加项目到你的收藏，就会在此处显示`],
  [`Add a website`, `添加网站`],
  [`Add account`, `添加帐户`],
  [`Add another`, `添加更多`],
  [`Add auto layout`, `添加自动布局`],
  [`Add background behind overlay`, `在叠加后添加背景`],
  [`Add comment (C)`, `添加评论（C）`],
  [`Add Description`, `添加简介`],
  [`Add Emoji`, `添加 Emoji 表情`],
  [`Add more seats`, `添加更多席位`],
  [`Add new folder`, `添加新文件夹`],
  [`Add new page`, `添加新页面`],
  [`Add New Property`, `添加新属性`],
  [`Add new variant`, `添加新变体`],
  [`Add New Variant`, `添加新变体`],
  [`Add new...`, `添加新的…`],
  [`Add or change your team’s logo or icon that appears on the team page and side navigation`, `添加或修改你的团队的标志或图标，会出现在团队页面和侧边导航`],
  [`Add or change your team’s public handle`, `添加或更改你的团队的公众账号`],
  [`Add profile connection`, `添加个人主页连接`],
  [`Add team members`, `添加团队成员`],
  [`Add to favorites`, `添加到收藏`],
  [`Add to Favorites`, `添加到收藏`],
  [`Add to library`, `添加到组件库`],
  [`Add to version history while editing.`, `当编辑时添加到历史版本`],
  [`Add to version history`, `添加到版本历史`],
  [`Add your collaborators`, `添加协作者`],
  [`Add/show comments pinned to a specific spot on the design`, `添加/显示被钉在设计上特定位置的评论。`],
  [`Add/Show comments`, `添加/显示评论`],
  [`Added`, `已添加`],
  [`Adjust font size`, `调整字号`],
  [`Adjust font weight`, `调整字重`],
  [`Adjust letter spacing`, `调整字距`],
  [`Adjust line height`, `调整行高`],
  [`Adjust`, `调整`],
  [`Admin dashboard`, `管理员仪表盘`],
  [`admin`, `管理员`],
  [`Admin`, `管理员`],
  [`Advanced options`, `高级选项`],
  [`Advanced stroke settings`, `高级描边设置`],
  [`Advanced stroke`, `高级描边`],
  [`After creating a team, you can invite others to join.`, `团队创建完成后，你可以邀请其他人加入。`],
  [`After delay`, `延迟触发`],
  [`After selecting points…`, `选择点后…`],
  [`Align bottom`, `下对齐`],
  [`Align center`, `居中对齐`],
  [`Align centers`, `居中对齐`],
  [`Align horizontal centers`, `水平居中`],
  [`Align left/right`, `左/右对齐`],
  [`Align left`, `左对齐`],
  [`Align middle`, `垂直居中`],
  [`Align right`, `右对齐`],
  [`Align top/bottom`, `上/下对齐`],
  [`Align top`, `上对齐`],
  [`Align vertical centers`, `垂直居中`],
  [`Align`, `对齐`],
  [`Alignment and padding`, `对齐和边距`],
  [`Alignment is now controlled from the auto layout parent frame.`, `现在可以通过自动布局父画框来控制对齐。`],
  [`Alignment is now set on the parent frame instead of on each independent object. And objects can be spaced evenly in a click. `, `现在，对齐方式是在父画框上设置，而不是在每个独立对象上设置。而且对象可以一键平均分布。`],
  [`Alignment`, `对齐`],
  [`All comments`, `全部评论`],
  [`All of your layers adjust the way you expect – no magic, you get full control.`, `你的所有图层都会按照你期望的方式进行调整 —— 不是什么魔法，你可以完全控制。`],
  [`All team files`, `所有团队文件`],
  [`All team projects`, `所有团队项目`],
  [`All Templates`, `所有模板`],
  [`All`, `全部`],
  [`Allow Figma to access your local fonts`, `允许 Figma 访问你的本地字体`],
  [`Allow viewers to copy, share, and export from this file`, `允许查看者复制、分享以及从这个文件中导出`],
  [`Alphabetical`, `字母顺序`],
  [`Alternate annotation forms`, `替代注释形式`],
  [`Alternate Half Widths`, `替代半宽`],
  [`Always open in Desktop App`, `总是在桌面应用中打开`],
  [`Always open in the App`, `总是在应用中打开`],
  [`An error occurred while opening the editor`, `打开编辑器时发生错误`],
  [`An error occurred while running this plugin`, `运行这个插件时发生错误`],
  [`An unknown error occurred`, `发生未知错误`],
  [`and`, `和`],
  [`Angular`, `角度渐变`],
  [`Animate`, `动画`],
  [`Animation`, `动画`],
  [`Annual billing only`, `仅限年付订单`],
  [`Annual plan`, `年付计划`],
  [`Anyone with the link`, `知道链接的任何人`],
  [`Anyone`, `所有人`],
  [`Are you sure you want to delete this comment? This action cannot be undone.`, `你确定要删除这条评论吗？这个操作不能撤销。`],
  [`Are you sure you want to move this project?`, `你确定要移动这个项目吗？`],
  [`Are you sure?`, `你确定吗？`],
  [`Arrange`, `排列`],
  [`Arrow tool`, `箭头工具`],
  [`Arrow`, `箭头`],
  [`As Typed`, `按输入`],
  [`Ascending`, `升序`],
  [`Ask the community`, `在社区中提问`],
  [`Assembling components and styles`, `正在合并组件和样式`],
  [`Assets`, `资产`],
  [`Author`, `作者`],
  [`Auto height`, `自动高度`],
  [`Auto layout added`, `已添加自动布局`],
  [`Auto layout alignment`, `自动布局对齐`],
  [`Auto Layout has`, `自动布局`],
  [`Auto layout`, `自动布局`],
  [`Auto width`, `自动宽度`],
  [`Auto`, `自动`],
  [`Back to files`, `返回文件列表`],
  [`Back`, `后退`],
  [`Background blur`, `背景模糊`],
  [`Background`, `背景`],
  [`Be respectful`, `保持尊重`],
  [`Bend tool`, `弯曲工具`],
  [`Best Practices`, `最佳实践`],
  [`Beta`, `测试`],
  [`Big nudge`, `大微调`],
  [`Billed annually or US$15 / editor / month`, `按年计费，或 15 美元/编辑者/月。`],
  [`Blank canvas`, `空白画布`],
  [`Blank Presets`, `空白预设`],
  [`Blend Mode`, `混合模式`],
  [`Blend`, `混合`],
  [`Blog`, `博客`],
  [`Blur`, `模糊`],
  [`Bold/Italic`, `加粗/斜体`],
  [`Bold`, `加粗`],
  [`Boolean groups`, `布尔组合`],
  [`Boosted by the Figma Team`, `由 Figma 团队驱动`],
  [`Borders`, `边框`],
  [`Bottom Center`, `底部中间`],
  [`Bottom left corner radius`, `下左圆角半径`],
  [`Bottom Left`, `下左`],
  [`Bottom padding`, `下边距`],
  [`Bottom right corner radius`, `下右圆角半径`],
  [`Bottom Right`, `下右`],
  [`Bottom`, `下`],
  [`Brainstorming`, `头脑风暴`],
  [`Brainstorms and sprints`, `头脑风暴和冲刺`],
  [`Bridge design and code with Variants`, `用变体在设计和代码之间架起桥梁`],
  [`Bring forward`, `上移一层`],
  [`Bring to front`, `移到顶层`],
  [`Browse `, `浏览 `],
  [`Browse all plugins ↓`, `浏览所有插件 ↓`],
  [`Browse All Plugins`, `浏览全部插件`],
  [`Browse all plugins`, `浏览所有插件`],
  [`Browse all templates on Community`, `浏览社区中的所有模板`],
  [`Browse creators`, `浏览创作者`],
  [`Browse libraries...`, `浏览组件库…`],
  [`Browse plugins in Community →`, `在社区中浏览插件 →`],
  [`Browse templates`, `浏览模板`],
  [`Build fully-responsive components with new Auto Layout updates. Stretch in any direction, control padding independently, and distribute objects evenly—all in an easier to use interface.`, `使用新的自动布局更新来构建完全响应的组件。在任何方向上拉伸，独立控制边距，并在一个更容易使用的界面中均匀地分配对象。`],
  [`Bulleted list`, `项目符号列表`],
  [`button.`, `按钮。`],
  [`can access`, `可以访问`],
  [`Can edit 1 file`, `可以编辑 1 个文件`],
  [`Can edit 2 files`, `可以编辑 2 个文件`],
  [`Can edit 3 files`, `可以编辑 3 个文件`],
  [`Can edit 4 files`, `可以编辑 4 个文件`],
  [`Can edit 5 files`, `可以编辑 5 个文件`],
  [`can edit`, `可以编辑`],
  [`Can edit`, `可以编辑`],
  [`can view prototype only`, `仅可以查看原型`],
  [`can view prototypes only`, `仅可以查看原型`],
  [`can view`, `可以查看`],
  [`Can view`, `可以查看`],
  [`Cancel Professional plan`, `取消专业版计划`],
  [`Cancel`, `取消`],
  [`Cap`, `端点`],
  [`Capital spacing`, `大写字母间隔`],
  [`Careers`, `工作机会`],
  [`Case-Sensitive Forms`, `大小写敏感形式`],
  [`Case`, `大小写`],
  [`Center`, `居中`],
  [`Centered`, `居中`],
  [`Change email`, `修改邮箱`],
  [`Change handle`, `修改账号`],
  [`Change icon`, `修改图标`],
  [`Change name`, `修改名字`],
  [`Change Name`, `修改名字`],
  [`Change password`, `修改密码`],
  [`Change profile handle`, `修改主页账号`],
  [`Change team icon`, `修改团队图标`],
  [`Change team name`, `修改团队名称`],
  [`Change to`, `修改为`],
  [`Change your team's name`, `修改你的团队的名称`],
  [`Change your unique profile handle`, `修改你独有的个人主页账号`],
  [`Changed`, `已修改`],
  [`Changes not yet published`, `未发布的更改`],
  [`Changes saved`, `更改已保存`],
  [`Character variant 1`, `字符变体 1`],
  [`Character variant 10`, `字符变体 10`],
  [`Character variant 2`, `字符变体 2`],
  [`Character variant 3`, `字符变体 3`],
  [`Character variant 4`, `字符变体 4`],
  [`Character variant 5`, `字符变体 5`],
  [`Character variant 6`, `字符变体 6`],
  [`Character variant 7`, `字符变体 7`],
  [`Character variant 8`, `字符变体 8`],
  [`Character variant 9`, `字符变体 9`],
  [`Character variants`, `字符变体`],
  [`Choose a channel...`, `选择一个频道…`],
  [`Choose a plan`, `选择一个计划`],
  [`Choose a slack channel to notify whenever someone comments on a file in the ‘`, `选择一个 Slack 频道，每当有人对“`],
  [`Choose Education`, `选择教育版`],
  [`Choose Image...`, `选择图片…`],
  [`Choose Image…`, `选择图片…`],
  [`Choose Organization`, `选择组织版`],
  [`Choose Professional`, `选择专业版`],
  [`Choose Starter`, `选择入门版`],
  [`Choose your team plan`, `选择你的团队方案`],
  [`Click + to replace mixed content.`, `点击 + 来替换多个内容。`],
  [`click the`, `请点击`],
  [`Click to Select`, `点击选择`],
  [`Click`, `点击`],
  [`click`, `点击`],
  [`Clip content`, `裁剪内容`],
  [`Close overlay`, `关闭叠加`],
  [`Close when clicking outside`, `点击空白处关闭`],
  [`code`, `代码`],
  [`Code`, `代码`],
  [`Collaborate in real time with your team and never worry about your files being up-to-date.`, `与你的团队实时协作，再也不用担心你的文件是不是最新的。`],
  [`Collaborate`, `协作`],
  [`Collaboration Features`, `协作能力`],
  [`Collaboration`, `协作`],
  [`Collapse layers`, `折叠图层`],
  [`Color burn`, `颜色加深`],
  [`Color conflict`, `颜色冲突`],
  [`Color dodge`, `颜色减淡`],
  [`Color Styles`, `颜色样式`],
  [`Color`, `颜色`],
  [`Colors`, `颜色`],
  [`Columns`, `列`],
  [`Combine as Variants`, `合并为变体`],
  [`Combine as variants`, `合并为变体`],
  [`Comment actions`, `评论操作`],
  [`Comment deleted`, `评论已删除`],
  [`Comment notification settings`, `评论通知设置`],
  [`Comment`, `评论`],
  [`Comments are here!`, `评论功能来啦！`],
  [`Comments from other users`, `来自别人的评论`],
  [`Comments left on my files and plugins`, `对我的文件和插件留下的评论`],
  [`Comments`, `评论`],
  [`Communicate clearly on a small scale with these carefully crafted and inspiring icons`, `用这些精心制作的、鼓舞人心的图标，在小范围内清晰地交流`],
  [`Community forum`, `社区论坛`],
  [`Community guidelines`, `社区准则`],
  [`Community Notifications`, `社区通知`],
  [`Community notifications`, `社区通知`],
  [`Community profile`, `社区个人主页`],
  [`Community`, `社区`],
  [`Community Spotlight`, `社区热点`],
  [`Compare`, `对比`],
  [`Component updates available`, `组件有更新`],
  [`Component`, `组件`],
  [`Components`, `组件`],
  [`Confirm and pay`, `确认并支付`],
  [`Congratulations!`, `干得漂亮！`],
  [`Connect multiple Figma accounts to use a single Community profile and merge multiple profiles into one. Publish content, follower creators, save likes, and receive notifications without having to switch accounts.`, `连接多个 Figma 账户以使用单一的社区配置文件，并将多个配置文件合并为一个。发布内容、关注创建者、保存喜欢的内容并接收通知，而无需切换账户。`],
  [`Connected apps`, `已连接的应用`],
  [`Connector`, `连线`],
  [`Constrain proportions`, `约束比例`],
  [`Constraints and Resizing`, `约束和调整大小`],
  [`Constraints`, `约束`],
  [`Contact a team admin to enable default libraries for your team.`, `联系团队管理员，为你的团队启用默认组件库。`],
  [`Contact sales`, `联系销售团队`],
  [`contact sales`, `联系销售团队`],
  [`Contact support`, `联系支持团队`],
  [`Contact`, `联系`],
  [`Content`, `内容`],
  [`Contents Only`, `仅内容`],
  [`Contextual Ligatures`, `上下文连字`],
  [`Continue to Payment`, `继续支付`],
  [`Continue`, `继续`],
  [`Contrast`, `对比度`],
  [`Control alignment at the parent level`, `在父级控制对齐`],
  [`Control their access with granular permissons and manage their access in one simple place.`, `通过精细的权限控制他们的访问，并在一个简单的地方管理他们的访问。`],
  [`Copied to clipboard`, `已复制到剪贴板`],
  [`Copy as CSS`, `复制为 CSS`],
  [`Copy as PNG`, `复制为 PNG`],
  [`Copy as SVG`, `复制为 SVG`],
  [`Copy as text`, `复制为文本`],
  [`Copy as`, `复制为`],
  [`Copy email`, `复制邮箱地址`],
  [`Copy link to page`, `复制页面链接`],
  [`Copy Link`, `复制链接`],
  [`Copy link`, `复制链接`],
  [`Copy properties`, `复制属性`],
  [`Copy/Paste`, `复制/粘贴`],
  [`Copy`, `复制`],
  [`Corner radius`, `圆角半径`],
  [`Corner smoothing`, `平滑圆角`],
  [`Count`, `边数`],
  [`Create a Community profile to publish publicly as your org or team`, `创建一个社区主页，以你的组织或团队的身份公开发布。`],
  [`Create a Figma Community profile to Like, Follow, and Publish`, `创建 Figma 社区个人主页，就可以点赞、关注和发布`],
  [`Create a new file to start from scratch. Import a Sketch file, PNG, or JPG by dragging and dropping.`, `创建一个新文件从头开始。可以拖拽导入 Sketch 文件、PNG 或 JPG 文件。`],
  [`Create a new personal access token:`, `创建新的个人访问令牌：`],
  [`Create a Professional Team`, `创建专业版团队`],
  [`Create a project`, `创建一个项目`],
  [`Create a Team to Publish Components`, `创建一个团队来发布组件`],
  [`Create a team`, `创建一个团队`],
  [`Create account`, `创建账号`],
  [`Create beautiful apps with mockups, templates, and mobile-friendly layouts`, `使用模型、模板和移动友好的布局创建漂亮的应用程序`],
  [`Create component`, `创建组件`],
  [`Create file in Drafts`, `在草稿中创建文件`],
  [`Create file`, `创建文件`],
  [`Create link`, `创建链接`],
  [`Create multiple components`, `创建多个组件`],
  [`Create new color style`, `创建新的颜色样式`],
  [`Create new effect style`, `创建新的效果样式`],
  [`Create new project`, `创建新项目`],
  [`Create new team`, `创建新的团队`],
  [`Create new text style`, `创建新的文本样式`],
  [`Create profile`, `创建主页`],
  [`Create project`, `创建项目`],
  [`Create scroll`, `创建`],
  [`Create style`, `新建样式`],
  [`Create team`, `创建团队`],
  [`Create teams to share design libraries with collaborators and organize files into Projects`, `创建团队，与协作者共享设计组件库，并将文件存放到项目中`],
  [`Create teams to share design libraries with collaborators and organize files into projects`, `创建团队，与合作者共享设计组件库，并将文件组织成项目。`],
  [`Created by `, `创建自 `],
  [`Created`, `创建时间`],
  [`Creating a connection`, `创建新的连接`],
  [`Creator`, `创作者`],
  [`Creators`, `创作者`],
  [`Crop image`, `裁剪图片`],
  [`Crop`, `裁切`],
  [`Current file is published`, `当前文件已发布`],
  [`Current file`, `当前文件`],
  [`Current name`, `当前名称`],
  [`Current version`, `当前版本`],
  [`Cursor chat`, `光标聊天框`],
  [`Cursor`, `光标`],
  [`Curve`, `曲线`],
  [`Custom libraries (Professional only)`, `自定义组件库（仅限专业版可用）`],
  [`Custom size`, `自定义大小`],
  [`Custom`, `自定义`],
  [`Customers`, `客户`],
  [`Cut`, `剪切`],
  [`Darken`, `变暗`],
  [`Dashes`, `虚线`],
  [`Date created`, `创建时间`],
  [`Date deleted`, `删除时间`],
  [`dbl-click`, `双击`],
  [`Decline`, `拒绝`],
  [`Decoration`, `文本修饰`],
  [`Decrease font size`, `减小字号`],
  [`Decrease font weight`, `减小字重`],
  [`Decrease indentation`, `减小缩进`],
  [`Decrease letter spacing`, `减小字距`],
  [`Decrease line height`, `减小行高`],
  [`Deep select within rectangle`, `矩形内穿透选择`],
  [`Deep select`, `穿透选择`],
  [`Default thumbnail restored`, `已恢复为默认封面`],
  [`Delay`, `延迟`],
  [`Delete  forever`, `永久删除`],
  [`Delete account`, `删除账号`],
  [`Delete and heal selection`, `删除和修复所选项`],
  [`Delete comment`, `删除评论`],
  [`Delete Community profile`, `删除社区个人主页`],
  [`Delete Forever`, `永久删除`],
  [`Delete forever`, `永久删除`],
  [`Delete page`, `删除页面`],
  [`Delete profile`, `删除主页`],
  [`Delete project`, `删除项目`],
  [`Delete public profile`, `删除公共主页`],
  [`Delete style`, `删除样式`],
  [`Delete team profile handle`, `删除团队主页账号`],
  [`Delete team`, `删除团队`],
  [`Delete version info`, `删除版本信息`],
  [`Delete your profile`, `删除你的个人主页`],
  [`Delete your team’s public profile`, `删除你的团队的公开主页`],
  [`Delete`, `删除`],
  [`Deleted `, `删除于 `],
  [`Deleted`, `已删除`],
  [`Deleting your profile will remove all your published files, plugins, likes, and follow data from Figma Community and relinquish your profile handle. This action can not be undone.`, `删除你的个人主页，将会从 Figma 社区中删除所有已发布的文件、插件、点赞和关注数据，并放弃你的个人主页账号。此操作无法撤销。`],
  [`Descending`, `降序`],
  [`Description`, `简介`],
  [`Design faster with lo-fi mockups, user flows, simple prototypes, and diagrams`, `使用低调的模拟图、用户流、简单的原型和图表来加快设计速度`],
  [`Design Features`, `设计能力`],
  [`Design file`, `设计文件`],
  [`Design on Windows`, `在 Windows 上设计`],
  [`Design System`, `设计系统`],
  [`Design Systems Features`, `设计系统能力`],
  [`Design Systems`, `设计系统`],
  [`Design systems`, `设计系统`],
  [`Design templates`, `设计模板`],
  [`Design the perfect website with wireframes, mockups, and responsive layouts`, `使用线框、模拟图和响应式布局设计完美的网站`],
  [`design`, `设计`],
  [`Design`, `设计`],
  [`Desktop`, `桌面端`],
  [`Detach instance`, `分离实例`],
  [`Detach style`, `分离样式`],
  [`Details`, `详情`],
  [`Developers`, `开发者`],
  [`Development`, `开发`],
  [`device.`, ` 设备上。`],
  [`Device`, `设备`],
  [`Diagramming`, `绘图`],
  [`Diamond`, `菱形渐变`],
  [`Difference`, `差集`],
  [`Disabled`, `已禁用`],
  [`Disabling interactive components improves prototype load times.`, `禁用交互式组件可以改善原型加载时间。`],
  [`Discover best practices and inspiring examples to design consistently and efficiently`, `发现最佳实践和鼓舞人心的例子，以实现一致和有效的设计`],
  [`Discover creators`, `发现创作者`],
  [`Discover new techniques through vector art, character designs, and photorealistic renderings`, `通过矢量艺术、角色设计和照片逼真的渲染发现新的技术`],
  [`Dismiss`, `忽略`],
  [`Display name`, `显示名称`],
  [`Dissolve`, `溶解`],
  [`Distances`, `距离`],
  [`Distribute bottom`, `向下均分`],
  [`Distribute horizontal centers`, `水平中心均分`],
  [`Distribute horizontal spacing`, `水平间距均分`],
  [`Distribute left`, `向左均分`],
  [`Distribute right`, `向右均分`],
  [`Distribute spacing`, `分布间距`],
  [`Distribute top`, `向上均分`],
  [`Distribute vertical centers`, `垂直中心均分`],
  [`Distribute vertical spacing`, `垂直间距均分`],
  [`Do Nothing`, `不用了`],
  [`Do you want to open this file in the Desktop App?`, `你希望一直在桌面应用中打开这个文件吗？`],
  [`Document colors`, `文件中的颜色`],
  [`Don't see a project? Try searching for it.`, `找不到项目？搜索一下试试看。`],
  [`Don’t see the one you want? Close this pop up and add your account from the account switcher first, then try again.`, `没有看到你想要的那个？关闭此弹窗，先从账户切换器中添加你的账户，然后再试。`],
  [`Done`, `完成`],
  [`Downgrade to viewer`, `降级为查看者`],
  [`Downgrade`, `降级`],
  [`Download installer to enable local fonts.`, `下载安装程序以启用本地字体。`],
  [`Download installer`, `下载安装程序`],
  [`Download the latest desktop app`, `下载最新的客户端应用`],
  [`Download uninstaller to disable local fonts.`, `下载卸载工具来禁用本地字体。`],
  [`Downloads`, `下载`],
  [`Drafts and teams`, `草稿和团队`],
  [`Drafts can only be shared with other viewers. To let others edit this file, move it to a team project first.`, `草稿只能分享给其他浏览者。要让其他人编辑这个文件，请先把它移到团队项目中。`],
  [`Drafts`, `草稿`],
  [`drag`, `拖动`],
  [`Drag`, `拖动`],
  [`Drawing Tools`, `绘画工具`],
  [`Drop shadow`, `投影`],
  [`Duplicate  to drafts`, `创建副本到草稿`],
  [`Duplicate page`, `创建页面副本`],
  [`Duplicate selection`, `创建选中项的副本`],
  [`Duplicate to drafts`, `创建副本到草稿`],
  [`Duplicate to your Drafts`, `创建副本到你的草稿`],
  [`Duplicate to your drafts`, `创建副本到你的草稿`],
  [`Duplicate`, `创建副本`],
  [`Duplicating...`, `正在创建副本…`],
  [`Duration`, `持续时间`],
  [`Ease In And Out Back`, `前后回动`],
  [`Ease In And Out`, `前后缓动`],
  [`Ease In Back`, `开始回动`],
  [`Ease In`, `前缓动`],
  [`Ease Out Back`, `结束回动`],
  [`Ease Out`, `后缓动`],
  [`Edit a file`, `编辑一个文件`],
  [`Edit Current Version`, `编辑当前版本`],
  [`Edit file page`, `编辑文件页面`],
  [`Edit hyperlink`, `编辑超链接`],
  [`Edit object`, `编辑对象`],
  [`Edit shape or image`, `编辑形状或图片`],
  [`Edit Style`, `编辑样式`],
  [`Edit style`, `编辑样式`],
  [`Edit this page`, `编辑此页面`],
  [`Edit Version Info`, `编辑版本信息`],
  [`Edit Version Information`, `编辑版本信息`],
  [`Edit...`, `编辑…`],
  [`Edit`, `编辑`],
  [`Edited `, `编辑于 `],
  [`Editor Seats`, `编辑者席位`],
  [`editor`, `个编辑者`],
  [`Editors on your team (`, `团队中的编辑者 (`],
  [`Editors on your team`, `团队中的编辑者`],
  [`Education team`, `教育版团队`],
  [`Education Team`, `教育版团队`],
  [`Education Verification`, `教育版认证`],
  [`Education`, `教育`],
  [`Effect settings`, `效果设置`],
  [`Effect Styles`, `效果样式`],
  [`Effect`, `效果`],
  [`Effects`, `效果`],
  [`Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions.`, `要么这个文件不存在，要么你没有权限查看它。请联系文件创建者核实链接或更新权限。`],
  [`Ellipse tool`, `椭圆工具`],
  [`Ellipse`, `椭圆`],
  [`Email me:`, `发邮件给我：`],
  [`Email`, `邮箱`],
  [`Emote`, `表情`],
  [`Enable and set default team libraries for all team files`, `启用并设置所有团队文件的默认团队组件库。`],
  [`Enable interactive components`, `启用交互式组件`],
  [`Enable libraries for all team files from your`, `为所有团队文件启用组件库，打开`],
  [`Enable libraries`, `启用组件库`],
  [`Enable non-Education editors by upgrading to a Professional team.`, `通过升级为专业团队，以启用非教育编辑者。`],
  [`Enable quick access to other libraries in this file. `, `可以快速访问该文件中的其他组件库。`],
  [`Enable quick access to other libraries in this file.`, `可以快速访问该文件中的其他组件库。`],
  [`Enable two-factor authentication...`, `启用两步验证…`],
  [`Enable two-factor authentication`, `启用两步验证`],
  [`Enable`, `启用`],
  [`Enabled libraries`, `已启用的组件库`],
  [`Enabling a team library will make it show up in all team files.`, `启用团队组件库将使其显示在所有团队文件中。`],
  [`Enter full screen (F)`, `进入全屏模式（F）`],
  [`Enter payment`, `输入付款方式`],
  [`Enterprise`, `企业`],
  [`Essential keyboard shortcuts`, `必备键盘快捷键`],
  [`Essential`, `必备`],
  [`Event:`, `事件：`],
  [`Events`, `活动`],
  [`Excellent files that just dropped recently`, `最近刚掉下来的优秀文件`],
  [`Exclude selection`, `差集所选项`],
  [`Exclusion`, `排除`],
  [`Explore Community`, `浏览社区`],
  [`Explore creators`, `浏览创作者`],
  [`Explore creatotr`, `发现创作者`],
  [`Explore files and plugins made just for Figma`, `探索专门为 Figma 制作的文件和插件`],
  [`Explore libraries...`, `查看组件库…`],
  [`Explore the nuances of fonts, type scales, lettering, and type design`, `探索字体、字体比例、字体和字体设计的细微差别`],
  [`Explore, install, use, and remix thousands of files and plugins`, `探索、安装、使用和演绎成千上万的文件和插件`],
  [`Explore`, `探索`],
  [`Export Disabled`, `导出已被禁用`],
  [`Export frames to PDF…`, `导出画框为 PDF…`],
  [`Export overlapping foreground and background layers when disabled`, `禁用时导出重叠的前景和背景图层。`],
  [`Export settings`, `导出设置`],
  [`Export your designs for use in production or to share with your team.`, `导出你的设计，以便在生产中使用或与你的团队分享。`],
  [`Export…`, `导出…`],
  [`export`, `导出`],
  [`Export`, `导出`],
  [`Exposure`, `曝光`],
  [`Family`, `字体`],
  [`Favorite`, `收藏`],
  [`Featured Plugins`, `精选插件`],
  [`Features`, `功能`],
  [`Feed`, `动态`],
  [`Feedback and retros`, `反馈和追溯`],
  [`Fig pick`, `Fig 精选`],
  [`FigJam file`, `FigJam 文件`],
  [`Figjam Resources`, `FigJam 资源`],
  [`FigJam templates`, `FigJam 模板`],
  [`Figma can export to PNG, JPEG, SVG, and PDF.`, `Figma 可以导出 PNG、JPEG、SVG 和 PDF。`],
  [`Figma Catan (Playable)`, `Figma 卡坦岛 (可玩)`],
  [`Figma Community`, `Figma 社区`],
  [`Figma helps teams create, test, and ship better designs from start to finish.`, `Figma 在全流程中帮助团队创建、测试和承载优秀设计。`],
  [`Figma is currently undergoing maintenance and will be temporarily unavailable.`, `Figma 目前正在进行维护，将暂时无法使用。`],
  [`Figma Multiplayer Dice Games!`, `Figma 多人骰子游戏！`],
  [`Figma Organization`, `Figma 组织`],
  [`Figma System`, `Figma 系统`],
  [`Figma will now autosave and apply your offline changes when you’re back online, even if you close your tab.`, `Figma 现在将自动保存并在你恢复在线时应用你的离线更改，即使你关闭你的标签页。`],
  [`File browser`, `文件浏览器`],
  [`File contributions`, `文件贡献`],
  [`File deleted forever`, `文件已永久删除`],
  [`File deleted`, `文件已删除`],
  [`File duplicated to your drafts`, `文件已创建副本到你的草稿`],
  [`File duplicated to your Drafts`, `文件已创建副本到你的草稿`],
  [`File duplicated`, `文件已创建副本`],
  [`File import failed`, `文件导入失败`],
  [`File imported successfully`, `文件导入成功`],
  [`File is temporarily view-only`, `文件暂时只允许查看`],
  [`File name`, `文件名`],
  [`File not found`, `找不到文件`],
  [`File notifications`, `文件通知`],
  [`File pinned to project`, `文件已在项目中置顶`],
  [`File restored`, `文件已恢复`],
  [`File`, `文件`],
  [`Files with edit access`, `有编辑权限的文件`],
  [`Files`, `文件`],
  [`Fill – Scale down or up to fill`, `填充 - 缩小或放大以填充`],
  [`Fill container`, `填充容器`],
  [`Fill`, `填充`],
  [`Final Forms`, `词尾形式`],
  [`Find and follow Figma creators to get their newest files and plugins`, `寻找并关注 Figma 创作者，获取他们最新的文件和插件`],
  [`Find next frame`, `查找下一个画框`],
  [`Find previous frame`, `查找上一个画框`],
  [`Fine-tune your designs with more layout options`, `用更多的布局选项微调你的设计`],
  [`Finish setup`, `完成设置`],
  [`Fit – Scale down to fit`, `适应 - 缩小以适应`],
  [`Fit`, `适应`],
  [`Fix position when scrolling`, `滚动时保持固定`],
  [`Fixed Height`, `固定高度`],
  [`Fixed height`, `固定高度`],
  [`Fixed size`, `固定大小`],
  [`Fixed Width`, `固定宽度`],
  [`Fixed width`, `固定宽度`],
  [`Fixed`, `固定`],
  [`Flag as inappropriate...`, `标记滥用…`],
  [`Flatten selection`, `拼合所选项`],
  [`Flatten`, `拼合`],
  [`Flip horizontal`, `水平翻转`],
  [`Flip objects while resizing`, `调整大小时翻转对象`],
  [`Flip vertical`, `垂直翻转`],
  [`Focus on the work, and don’t spam or post unrelated links. If you do, we’ll remove ‘em.`, `专注于工作，不要发垃圾邮件或发布不相关的链接。如果你这样做，我们会删除它们。`],
  [`Follow`, `关注`],
  [`Follower`, ` 关注者`],
  [`Followers`, ` 关注者`],
  [`followers`, ` 关注者`],
  [`Following`, `正在关注`],
  [`Follows you`, `关注了你`],
  [`Font default`, `字体默认`],
  [`Font doesn’t support small caps`, `字体不支持小型大写字母`],
  [`Font doesn’t support subscript`, `字体不支持下标`],
  [`Font doesn’t support superscript`, `字体不支持上标`],
  [`Font size`, `字体大小`],
  [`Font`, `字体`],
  [`Fonts`, `字体`],
  [`fonts available in Figma.`, `种字体可用于 Figma。`],
  [`for all files in your drafts.`, `给所有草稿里的文件。`],
  [`for all team files.`, ` 给所有团队文件。`],
  [`for as long as you're a verified Education user`, ` 只要你是验证过的教育用户。`],
  [`For individuals`, `个人`],
  [`For scrolling to work on this frame, the content needs to be bigger than the frame.`, `为了让滚动在这个画框上可用，内容需要比画框大。`],
  [`For teams`, `团队`],
  [`for up to 2 editors and 3 projects`, `最多支持 2 个编辑者和 3 个项目`],
  [`Forced small caps`, `强制小型大写字母`],
  [`Fraction denominators`, `分数分母`],
  [`Fraction numerators`, `分数数字`],
  [`Fractions`, `分数`],
  [`Frame outlines`, `画框轮廓`],
  [`Frame selection`, `添加画框`],
  [`Frame tool`, `画框工具`],
  [`Frame`, `画框`],
  [`Free for students and educators`, `学生和教育工作者免费`],
  [`Free`, `免费`],
  [`Frequently Used`, `常用`],
  [`Full widths`, `全宽`],
  [`Fun activities`, `趣味活动`],
  [`Get desktop app`, `下载桌面版应用`],
  [`Get feedback, requests, and copy updates where you’ll use them, not in your inbox.`, `在你使用的时候就获取反馈、请求和副本更新，而不是在你的收件箱。`],
  [`Get help`, `获取帮助`],
  [`Get notifications in Slack`, `在 Slack 中接收通知`],
  [`Get started with your team's design system by creating libraries of shared colors, styles, and components. This project already has a set of colors published to your team.`, `通过创建共享的颜色、样式和组件库，开始使用你的团队设计系统。这个项目已经有一套颜色发布给你的团队。`],
  [`Get Started`, `开始使用`],
  [`Get started`, `开始使用`],
  [`Give feedback, ask a question, or just leave a note of appreciation. Click anywhere in the file to leave a comment.`, `给予反馈，提出问题，或只是留下鼓励的话。点击文件中的任意位置，即可留下评论。`],
  [`Go to frame`, `转到画框`],
  [`Go to main component`, `转到组件母版`],
  [`Gold`, `金色`],
  [`Got it`, `好的`],
  [`Grab a color from elsewhere without losing your flow`, `从任意位置抓取颜色而不中断工作流`],
  [`Graphic Design`, `视觉设计`],
  [`Grid Styles`, `网格样式`],
  [`Grid`, `网格`],
  [`Group selection`, `编组所选项`],
  [`Group`, `分组`],
  [`Gutter`, `间距`],
  [`Half widths`, `半宽`],
  [`Hand tool`, `抓手工具`],
  [`Hard light`, `强光`],
  [`Height`, `高`],
  [`Help and account`, `帮助和账户`],
  [`Help and resources`, `帮助和资源`],
  [`Help center`, `帮助中心`],
  [`Help Center`, `帮助中心`],
  [`Help page`, `帮助页面`],
  [`Help people discover your file:`, `帮助大家找到你的文件：`],
  [`Help users easily explore landing pages, carousels, and more. Scroll to selected objects or layers by dragging a connection within the same top-level frame.`, `帮助用户轻松探索登录页面、转盘等。通过拖动同一顶层画框内的连接，滚动到选定的对象或图层。`],
  [`Help`, `帮助`],
  [`Hide canvas UI during changes`, `在更改期间隐藏画布 UI`],
  [`Hide other layers`, `隐藏其余图层`],
  [`Hide version history`, `隐藏历史版本`],
  [`Highlight layers on hover`, `突出显示悬停图层`],
  [`Highlights`, `高光`],
  [`Historical Forms`, `历史形式`],
  [`Historical Ligatures`, `历史连字`],
  [`Hold up...`, `稍等一下…`],
  [`Horizontal and vertical scrolling`, `水平 & 垂直滚动`],
  [`Horizontal direction`, `水平方向`],
  [`Horizontal Padding`, `水平间距`],
  [`Horizontal scrolling`, `水平滚动`],
  [`Horizontal spacing`, `水平间距`],
  [`Horizontal`, `水平`],
  [`Hover`, `悬停`],
  [`Hue`, `色相`],
  [`Hug contents`, `适应内容`],
  [`Icons`, `图标`],
  [`If you are an admin of a Starter Team, you can upgrade it to an Education Team. Just choose the "Education Plan” when upgrading your team.`, `如果你是入门版团队的管理员，你可以将其升级为教育团队。只要在升级团队时选择 "教育计划 "即可。`],
  [`Ignore constraints (frames only)`, `忽略约束（仅画框）`],
  [`Illustrations`, `插画`],
  [`Illustrators you should follow`, `你应该关注的插画师`],
  [`Image Resized`, `图片已缩放`],
  [`Image`, `图片`],
  [`Import canceled.`, `已取消导入。`],
  [`Import files`, `导入文件`],
  [`Import Sketch files`, `导入 Sketch 文件`],
  [`Import`, `导入`],
  [`Importing file...`, `正在导入文件…`],
  [`In development`, `正在开发`],
  [`Inactive`, `不活跃`],
  [`Increase font size`, `增大字号`],
  [`Increase font weight`, `增大字重`],
  [`Increase indentation`, `增大缩进`],
  [`Increase letter spacing`, `增大字距`],
  [`Increase line height`, `增大行高`],
  [`Independent corners`, `独立圆角`],
  [`Individual padding for more precise layouts`, `独立的边距使布局更精确`],
  [`Initial Forms`, `词首形式`],
  [`Inner border`, `内边框`],
  [`Inner shadow`, `内阴影`],
  [`Inside`, `内部`],
  [`inspect`, `检查`],
  [`Install Font Helper`, `安装字体帮助程序`],
  [`Install`, `安装`],
  [`Installed`, `已安装`],
  [`Installs`, `安装`],
  [`Instance options`, `组件实例选项`],
  [`Instance`, `组件实例`],
  [`Instant`, `即时`],
  [`Integrations`, `集成`],
  [`Interaction details`, `交互细节`],
  [`Interaction`, `交互`],
  [`Interactions`, `交互`],
  [`Interactive components  `, `交互式组件`],
  [`Internal profile`, `内部个人主页`],
  [`Intersect selection`, `交集所选项`],
  [`Invert zoom direction`, `反转缩放方向`],
  [`Invite email sent again!`, `邀请邮件已再次发送`],
  [`Invite members`, `邀请成员`],
  [`Invite someone…`, `邀请某人…`],
  [`Invite team members`, `邀请团队成员`],
  [`Invite to team`, `邀请加入团队`],
  [`Invite-only — let me choose who has access`, `仅限邀请 - 让我选择谁可以访问`],
  [`Invite-only`, `仅限邀请`],
  [`Invite`, `邀请`],
  [`Isolated Forms`, `独立形式`],
  [`Italic`, `斜体`],
  [`Join beta`, `加入测试版`],
  [`Join selection`, `连接所选项`],
  [`Join`, `节点`],
  [`Just drag your Sketch files onto the browser and we’ll convert them to Figma for you.`, `只需将你的 Sketch 文件拖到浏览器上，我们将为你转换为 Figma 文件。`],
  [`just now`, `刚刚`],
  [`Keep things respectful and constructive. We love free expression and healthy debate, but we’ll suspend or remove you for posting abusive or vulgar comments.`, `保持尊重和建设性的态度。我们喜欢自由的表达和健康的辩论，但我们会暂停或删除你发布的辱骂或粗俗的评论。`],
  [`Keep tool selected after use`, `使用后保持工具选择`],
  [`Kerning pairs`, `字偶距组合`],
  [`Kerning`, `字偶距`],
  [`Key/gamepad`, `键盘/游戏手柄`],
  [`Key`, `按键`],
  [`Keyboard shortcuts`, `键盘快捷键`],
  [`Keyboard zooms into selection`, `键盘缩放所选项`],
  [`Landscape`, `横屏`],
  [`Last active: All`, `最近活跃：全部`],
  [`Last active: More than 3 months ago`, `最近活跃：超过 3 个月前`],
  [`Last active: More than 30 days ago`, `最近活跃：超过 30 天前`],
  [`Last active: More than 7 days ago`, `最近活跃：超过 7 天前`],
  [`Last active`, `最近更新`],
  [`Last activity`, `最近更新`],
  [`Last modified`, `最后修改`],
  [`Last month`, `上个月`],
  [`last month`, `上个月`],
  [`Last updated `, `最近更新：`],
  [`Last updated`, `最近更新`],
  [`Last viewed`, `最近浏览`],
  [`last year`, `去年`],
  [`Later`, `稍后`],
  [`Layer blur`, `图层模糊`],
  [`Layer`, `图层`],
  [`Layers Panel`, `图层面板`],
  [`Layers`, `图层`],
  [`Layout grid`, `布局网格`],
  [`Layout grids hidden`, `隐藏布局网格`],
  [`Layout grids visible`, `显示布局网格`],
  [`Layout grids`, `布局网格`],
  [`Learn more →`, `了解更多 →`],
  [`Learn more about team plans`, `了解更多关于团队计划的信息`],
  [`Learn more…`, `了解更多…`],
  [`Learn more...`, `了解更多…`],
  [`Learn more`, `了解更多`],
  [`Leave notes right in your design files.`, `在你的设计文件中直接留下信息。`],
  [`Leave team`, `离开团队`],
  [`Leave`, `离开`],
  [`leave`, `离开`],
  [`Left & Right`, `左 & 右`],
  [`Left and right`, `左右拉伸`],
  [`Left padding`, `左边距`],
  [`Left`, `左`],
  [`Legal summary`, `法律摘要`],
  [`Let others edit this file with you?`, `让别人和你一起编辑这个文件吗？`],
  [`Letter case`, `字母大小写`],
  [`Letter spacing`, `字距`],
  [`Letterforms`, `字母形式`],
  [`Libraries`, `组件库`],
  [`Library`, `组件库`],
  [`License`, `授权`],
  [`Licensed under `, `授权协议：`],
  [`Ligatures`, `连字`],
  [`Lighten`, `变亮`],
  [`Liked plugin!`, `已点赞插件！`],
  [`Likes`, `点赞`],
  [`Line Arrow`, `线性箭头`],
  [`Line height`, `行高`],
  [`Line style`, `线条样式`],
  [`Line tool`, `直线工具`],
  [`Line`, `直线`],
  [`Linear`, `线性渐变`],
  [`Link copied to clipboard`, `链接已复制到剪贴板`],
  [`Link deleted`, `链接已删除`],
  [`Link to selected frame`, `链接到已选中的画框`],
  [`List style`, `列表样式`],
  [`Live device preview`, `实时设备预览`],
  [`Local colors`, `本地颜色`],
  [`Local components`, `本地组件`],
  [`Local fonts are currently not enabled.`, `本地字体目前尚未启用。`],
  [`Local fonts are enabled. You have `, `本地字体已启用。你有`],
  [`Local styles`, `本地样式`],
  [`Lock/Unlock selection`, `锁定/解锁所选项`],
  [`Lock/Unlock`, `锁定/解锁`],
  [`Log in`, `登录`],
  [`Log out of all accounts`, `退出所有账号`],
  [`Log Out`, `退出`],
  [`Log out`, `退出`],
  [`Lower case`, `小写`],
  [`Lowercase`, `小写`],
  [`Luminosity`, `明度`],
  [`Main component`, `组件母版`],
  [`Manage plugins…`, `管理插件…`],
  [`Manage Slack notifications`, `管理 Slack 通知`],
  [`Manual`, `手动`],
  [`Margin`, `边距`],
  [`Mark all as read`, `全部标记为已读`],
  [`Marker`, `马克笔`],
  [`Mask outlines hidden`, `隐藏蒙版轮廓`],
  [`Mask outlines visible`, `显示蒙版轮廓`],
  [`Mask outlines`, `蒙版轮廓`],
  [`Mask`, `蒙版`],
  [`Math`, `数学`],
  [`Mathematical Greek`, `数学希腊字符`],
  [`Maybe later`, `稍后再说`],
  [`Measure to selection`, `测量到所选项的距离`],
  [`Medial Forms`, `词中形式`],
  [`Meeting notes`, `会议记录`],
  [`Members`, `成员`],
  [`Midnight Green`, `午夜绿`],
  [`Mirror angle and length`, `角度与长度对称`],
  [`Mirror angle`, `角度对称`],
  [`Missing Font`, `字体丢失`],
  [`Missing Fonts`, `字体丢失`],
  [`Missing fonts`, `字体丢失`],
  [`Miter Angle`, `斜度`],
  [`Mixed`, `多个值`],
  [`Mobile Design`, `移动端设计`],
  [`Mobile design`, `移动端设计`],
  [`Model`, `型号`],
  [`Monospace lowercase/old-style`, `等宽小写字母/不等高`],
  [`Monospace uppercase/lining`, `等宽大写字母/等高`],
  [`Monthly Plan`, `月付计划`],
  [`More features`, `更多功能`],
  [`More Options`, `更多选项`],
  [`More than 3 months ago`, `超过 3 个月前`],
  [`More than 30 days ago`, `超过 30 天前`],
  [`More than 7 days ago`, `超过 7 天前`],
  [`more...`, `更多…`],
  [`More`, `更多`],
  [`Mouse down`, `按下鼠标时`],
  [`Mouse enter`, `鼠标进入`],
  [`Mouse leave`, `鼠标离开`],
  [`Mouse up`, `释放鼠标时`],
  [`Move Down`, `下移`],
  [`Move file`, `移动文件`],
  [`Move in`, `移入`],
  [`Move Left`, `左移`],
  [`Move out`, `移出`],
  [`Move project`, `移动项目`],
  [`Move Right`, `右移`],
  [`Move this file to a Professional team in order to publish components to that team's library.`, `将此文件移动到专业团队，以便将组件发布到该团队的库中。`],
  [`Move to page`, `移到页面`],
  [`Move to project…`, `移动到项目…`],
  [`Move to project...`, `移动到项目…`],
  [`Move to project`, `移动到项目`],
  [`Move to team to publish components`, `移动到团队来发布组件`],
  [`Move to team...`, `移动到团队…`],
  [`Move to team`, `移动到团队`],
  [`Move Tool`, `移动工具`],
  [`Move tool`, `移动工具`],
  [`Move Tools`, `移动工具`],
  [`Move Up`, `上移`],
  [`Move while resizing`, `调整大小时移动`],
  [`Move`, `移动`],
  [`Multiplayer cursors hidden`, `隐藏多人鼠标指针`],
  [`Multiplayer cursors visible`, `显示多人鼠标指针`],
  [`Multiplayer cursors`, `多人鼠标指针`],
  [`Multiplayer`, `多用户`],
  [`Multiply`, `正片叠底`],
  [`Name this version`, `给这个版本命名`],
  [`Name your team`, `给团队取个名字`],
  [`Name`, `名字`],
  [`Navigate to`, `导航到`],
  [`new & noteworthy`, `新增 & 值得注意`],
  [`New design file`, `新建设计文件`],
  [`New FigJam file`, `新建 FigJam 文件`],
  [`New file creation`, `新文件创建`],
  [`New file`, `新建文件`],
  [`New from Sketch file…`, `从 Sketch 文件新建…`],
  [`New Page`, `新建页面`],
  [`New Plugin...`, `新建插件…`],
  [`New project`, `新建项目`],
  [`New Team…`, `新建团队…`],
  [`New Team...`, `新建团队…`],
  [`New`, `新建`],
  [`Next page`, `下一页`],
  [`Next to review`, `下一步并检查`],
  [`Next`, `下一个`],
  [`No `, `没有`],
  [`No files yet.`, `还没有文件。`],
  [`No list`, `无列表`],
  [`No members to show.`, `没有可显示的成员。`],
  [`No mirroring`, `不对称`],
  [`No projects yet`, `还没有项目`],
  [`No results found`, `没有找到结果`],
  [`No scrolling`, `无滚动`],
  [`No selected layers have export settings. Click + in the export section of the properties panel to add one.`, `选中的图层都没有设置导出。在属性面板的导出部分点击 + 来添加一个。`],
  [`No syncing, no waiting, no merge conflicts.`, `无需同步、无需等待、无需合并冲突。`],
  [`No team permissions`, `没有团队权限`],
  [`No team-level permissions`, `没有团队级权限`],
  [`No updates available`, `无可用更新`],
  [`None`, `无`],
  [`Normal`, `正常`],
  [`Not applicable for selected text`, `不适用于选定的文本`],
  [`Nothing liked yet`, `没有点赞任何内容`],
  [`Nothing published yet`, `没有发布任何内容`],
  [`Notifications`, `通知`],
  [`Now you can leave kudos, feedback, or questions for your fellow Figma creators.`, `现在，你可以为你的 Figma 创作者朋友留下赞誉、反馈或问题。`],
  [`Now, they’re both simpler and more powerful – paths finally work the way they should.`, `现在，它们既简单又强大，路径最终将按该有的方式工作。`],
  [`Nudge amount…`, `单位微调…`],
  [`Nudge amount`, `单位微调`],
  [`Number `, `数字`],
  [`Numbered list`, `编号列表`],
  [`Numbers`, `数字`],
  [`Object`, `对象`],
  [`Objects can now be set to fill container, hug contents, and fixed on both axes. `, `对象现在可以设置为填充容器，紧贴内容，并固定在两个轴上。`],
  [`Offline changes will be synced with Figma when you go online.`, `离线更改将在你上线时与 Figma 同步。`],
  [`Offset`, `偏置`],
  [`OK`, `好的`],
  [`Okay`, `好的`],
  [`On click`, `单击`],
  [`On drag`, `拖动`],
  [`On tap`, `轻触`],
  [`One of the coolest things about Figma is that you don’t have to start from scratch to get to work.`, `Figma 最酷的一点是，你不必从头开始工作。`],
  [`Only members of Professional Teams can publish components to a shared library. Create a new team or join an existing team to use this feature.`, `只有专业团队的成员才能将组件发布到共享库中。创建一个新的团队或加入一个现有的团队来使用此功能。`],
  [`Only people invited to this file`, `只有被邀请的人`],
  [`Only team admins can enable libraries for the team.`, `只有团队管理员才能为团队启用组件库。`],
  [`Only you can edit drafts. To let others edit this file with you, move it to a team project first.`, `只有你可以编辑草稿。要想让其他人和你一起编辑这个文件，请先把它移到团队项目中。`],
  [`Only yours `, `仅我的`],
  [`Only yours`, `仅我的`],
  [`Opacity`, `不透明度`],
  [`Open a file to learn more about Figma’s powerful editing features!`, `打开一个文件，了解更多关于 Figma 强大的编辑功能！`],
  [`Open admin dashboard`, `打开管理员仪表盘`],
  [`Open assets panel`, `打开资源面板`],
  [`Open code panel`, `打开代码面板`],
  [`Open console`, `打开控制台`],
  [`Open design panel`, `打开设计面板`],
  [`Open files in the Desktop App from now on?`, `从现在开始都在桌面应用中打开文件吗？`],
  [`Open font settings`, `打开字体设置`],
  [`Open in App`, `应用中打开`],
  [`Open in desktop app`, `在桌面应用中打开`],
  [`Open in Editor`, `在编辑器中打开`],
  [`Open in new tab`, `在新标签页中打开`],
  [`Open inspect panel`, `打开检查面板`],
  [`Open layers panel`, `打开图层面板`],
  [`Open link`, `打开链接`],
  [`Open links in desktop app`, `在桌面应用打开链接`],
  [`Open original file`, `打开原始文件`],
  [`Open overlay`, `打开叠加`],
  [`Open playground`, `打开游乐场`],
  [`Open prototype panel`, `打开原型面板`],
  [`Open the playground`, `打开游乐场`],
  [`Open to sync`, `打开并同步`],
  [`Open View Only`, `仅查看模式打开`],
  [`Open`, `打开`],
  [`Options`, `选项`],
  [`or`, `或者`],
  [`Order`, `顺序`],
  [`Ordinals`, `序数字`],
  [`Organization`, `组织版`],
  [`Organize your design system with Variants so even the most complex components are structured intuitively. Combine variations of the same component and simplify your asset library.`, `使用变体组织你的设计系统，因此即使是最复杂的组件也能直观地组织起来。结合同一组件的变体，简化你的资产库。`],
  [`Original case`, `初始大小写`],
  [`Other options`, `其他选项`],
  [`Others`, `其他人`],
  [`Outer Border`, `外边框`],
  [`Outline stroke`, `轮廓化描边`],
  [`Outline Text`, `轮廓化文本`],
  [`Outlines hidden`, `隐藏轮廓`],
  [`Outlines visible`, `显示轮廓`],
  [`Outlines`, `轮廓`],
  [`Outside`, `外部`],
  [`Overflow behavior`, `溢出行为`],
  [`Overlay`, `叠加`],
  [`Owner`, `创建者`],
  [`owner`, `创建者`],
  [`Pack horizontal`, `水平堆叠`],
  [`Pack vertical`, `垂直堆叠`],
  [`Packed`, `堆叠`],
  [`Padding around items`, `内边距`],
  [`Page deleted`, `页面已删除`],
  [`Page duplicated`, `已创建页面副本`],
  [`Page:`, `页面：`],
  [`Pages`, `页面`],
  [`Paint bucket`, `颜料桶`],
  [`Pan`, `抓手`],
  [`Panels`, `面板`],
  [`Paper`, `纸张`],
  [`Paragraph indent`, `段落缩进`],
  [`Paragraph spacing`, `段落间距`],
  [`Parent component`, `父级组件`],
  [`Pass through`, `穿透`],
  [`Password`, `密码`],
  [`Paste and match style`, `粘贴并匹配样式`],
  [`Paste over selection`, `粘贴至所选位置`],
  [`Paste properties`, `粘贴属性`],
  [`Paste to replace`, `粘贴替换`],
  [`Paste`, `粘贴`],
  [`Pasting...`, `正在粘贴…`],
  [`Pen tool`, `钢笔工具`],
  [`Pen tools have always been scary to use because they can be touchy and fragile.`, `一直以来，钢笔工具都是让人害怕的，因为它们既敏感又脆弱。`],
  [`Pen`, `钢笔`],
  [`Pencil tool`, `铅笔工具`],
  [`Pencil`, `铅笔`],
  [`People who have edited this project will appear here.`, `编辑过这个项目的人将出现在这里。`],
  [`People`, `人员`],
  [`per editor when billed annually`, `每个编辑者（年付）`],
  [`per editor, annual billing only`, `每个编辑者（仅限年付）`],
  [`Permanently delete this team and all resources within`, `永久性地删除这个团队和其中的所有资源`],
  [`Permissions`, `授权`],
  [`Personal access tokens allow you to access your own data via the API. Do not give out your personal access tokens to anybody who you don't want to access your files.`, `个人访问令牌允许你通过API访问你自己的数据。请不要将你的个人访问令牌提供给任何你不想访问你的文件的人。`],
  [`Personal access tokens`, `个人访问令牌`],
  [`Phone`, `手机`],
  [`Pick color`, `吸取颜色`],
  [`Pick the account you want to connect`, `选择你要连接的账户`],
  [`Pin to project`, `在项目中置顶`],
  [`Pinned`, `已置顶`],
  [`Pixel grid hidden`, `隐藏像素网格`],
  [`Pixel grid visible`, `显示像素网格`],
  [`Pixel grid`, `像素网格`],
  [`Pixel preview disabled`, `像素预览已禁用`],
  [`Pixel preview enabled (1x)`, `像素预览已启用 (1x)`],
  [`Pixel preview enabled (2x)`, `像素预览已启用 (2x)`],
  [`Pixel preview`, `像素预览`],
  [`Place image…`, `放置图片…`],
  [`Plan and billing`, `计划和计费`],
  [`Planning and Retros`, `规划和回溯`],
  [`Please confirm your email address`, `请确认你的邮件地址`],
  [`Plugin / file cover`, `插件 / 文件封面`],
  [`Plugin administration`, `插件管理`],
  [`Plugin icon`, `插件图标`],
  [`Plugin installed`, `插件安装完成`],
  [`Plugin`, `插件`],
  [`Plugins`, `插件`],
  [`Polygon`, `多边形`],
  [`Popular`, `流行`],
  [`Portrait`, `竖屏`],
  [`Position`, `位置`],
  [`Post`, `确定`],
  [`Preferences`, `偏好设置`],
  [`Present`, `演示`],
  [`Presentation`, `演示`],
  [`Presentations`, `演示文稿`],
  [`Preserve scroll position`, `滚动时固定位置`],
  [`Presets`, `预设`],
  [`Press it now to quickly hide the panes and focus on your work`, `现在按下它可以快速隐藏面板，专注于你的工作`],
  [`Press`, `按下`],
  [`Preview as a`, `预览形式`],
  [`Preview`, `预览`],
  [`Previous page`, `上一页`],
  [`Pricing FAQ`, `价格常见问题`],
  [`Pricing`, `定价`],
  [`Primary email`, `首选邮箱`],
  [`Privacy`, `隐私`],
  [`Professional`, `专业版`],
  [`Profile banner`, `个人主页横幅`],
  [`Profile connections`, `个人主页连接`],
  [`Profile deleted.`, `账号已删除。`],
  [`Profile`, `个人主页`],
  [`Project name`, `项目名称`],
  [`Project`, `项目`],
  [`Projects contain your design files. Let’s create your first project now.`, `项目包含你的设计文件。现在让我们来创建你的第一个项目。`],
  [`Projects help you organize designs and makes sharing easier. Start a new project to share with your teammates.`, `项目可以帮助你组织设计文件，且更容易分享。开始一个新的项目并分享给你的队友。`],
  [`Projects with edit access`, `有编辑权限的项目`],
  [`Projects`, `项目`],
  [`Properties`, `属性`],
  [`Property defaults updated`, `属性默认值已更新`],
  [`Proportional Alternate Widths`, `比例替代宽度`],
  [`Proportional lowercase/old-style`, `比例小写字母/不等高`],
  [`Proportional uppercase/lining`, `比例大写字母/等高`],
  [`Proportional widths`, `变宽`],
  [`Prototype`, `原型`],
  [`prototype`, `原型`],
  [`Prototyping Features`, `原型设计能力`],
  [`Prototyping`, `原型设计`],
  [`Public profile:`, `公众个人主页：`],
  [`Public profile`, `公开个人主页`],
  [`Public`, `公开`],
  [`Publish a version of this file to the Community for the public to duplicate and remix.`, `向社区发布该文件的一个版本，供大家复制和重新演绎。`],
  [`Publish changes`, `发布更改`],
  [`Publish file`, `发布文件`],
  [`Publish library`, `发布组件库`],
  [`Publish styles & components`, `发布样式和组件`],
  [`Publish styles and components`, `发布样式和组件`],
  [`Publish styles only`, `仅发布样式`],
  [`Publish styles`, `发布样式`],
  [`Publish to Community`, `发布到社区`],
  [`Publish update...`, `发布更新…`],
  [`Publish your changes to your team library.`, `将你的更改发布到你的团队组件库中。`],
  [`Publish...`, `发布…`],
  [`Publish`, `发布`],
  [`Published and up to Date`, `已发布且为最新`],
  [`Published and up to date`, `已发布且为最新`],
  [`Published`, `已发布时间`],
  [`Publisher`, `发布者`],
  [`Publishing library`, `正在发布组件库`],
  [`Push overrides to main component`, `覆盖组件母版`],
  [`Push`, `推动`],
  [`Quick actions…`, `快速操作…`],
  [`Radial`, `径向渐变`],
  [`Radius`, `圆角`],
  [`Randomize`, `随机化`],
  [`Rare ligatures`, `罕见连字`],
  [`Rasterize selection`, `像素化所选项`],
  [`Read more`, `阅读全文`],
  [`Read our`, `阅读我们的`],
  [`Ready to upgrade your plan?`, `准备升级你的计划？`],
  [`Recent contributors`, `最近贡献者`],
  [`Recent files from creators like you`, `来自像你这样的创作者的最新文件`],
  [`Recent projects`, `近期项目`],
  [`Recent`, `最近`],
  [`Recently viewed`, `最近浏览`],
  [`Rectangle tool`, `矩形工具`],
  [`Rectangle`, `矩形`],
  [`Redo`, `重做`],
  [`Region Tools`, `区域工具`],
  [`Related components`, `相关组件`],
  [`Related tags`, `相关标签`],
  [`Release notes`, `版本说明`],
  [`Releases`, `版本`],
  [`Relevance`, `相关`],
  [`Remote Design Sprinting (RDS)`, `远程设计冲刺（RDS）`],
  [`Remote Design`, `远程设计`],
  [`Remove all connections`, `移除全部连接`],
  [`Remove auto layout`, `移除自动布局`],
  [`Remove connections`, `移除连接`],
  [`Remove file from library`, `将文件从组件库移除`],
  [`Remove fill`, `移除填充`],
  [`Remove from favorites`, `从收藏夹中移除`],
  [`Remove from library`, `从组件库移除`],
  [`Remove from pinned`, `从置顶中移除`],
  [`Remove from recent`, `从最近中移除`],
  [`Remove mask`, `移除蒙版`],
  [`Remove property`, `移除属性`],
  [`Remove stroke`, `移除描边`],
  [`remove team access`, `移除团队访问权限`],
  [`Remove...`, `移除…`],
  [`Remove`, `移除`],
  [`remove`, `移除`],
  [`Removing a connection`, `删除连接`],
  [`Rename duplicated layers`, `重命名已创建的副本图层`],
  [`Rename page`, `重命名页面`],
  [`Rename selection`, `重命名所选项`],
  [`Rename team`, `重命名团队`],
  [`Rename`, `重命名`],
  [`Replace Fonts`, `替换字体`],
  [`Replacement`, `替换字体`],
  [`Replies to my comments`, `对我的评论的回复`],
  [`Reply`, `回复`],
  [`Report a bug`, `反馈 Bug`],
  [`Report comment...`, `投诉评论…`],
  [`Resend Email`, `重新发送邮件`],
  [`Resend invite`, `重新发送邀请`],
  [`Resend Invite`, `重新发送邀请`],
  [`resend`, `重新发送`],
  [`Reset all overrides`, `重置所有覆盖`],
  [`Reset effects`, `重置效果`],
  [`Reset exports`, `重置导出`],
  [`Reset fill`, `重置填充`],
  [`Reset filters`, `重置过滤器`],
  [`Reset instance`, `重置组件实例`],
  [`Reset name`, `重置名称`],
  [`Reset onboarding`, `重置新手引导`],
  [`Reset others`, `重置其他`],
  [`Reset overlay`, `重置叠加`],
  [`Reset overrides`, `重置覆盖`],
  [`Reset size`, `重置大小`],
  [`Reset stroke`, `重置描边`],
  [`Reset text style`, `重置文本样式`],
  [`Reset text`, `重置文本`],
  [`Reset transition`, `重置过渡`],
  [`Reset visibility`, `重置可见性`],
  [`Resize from center`, `从中心调整大小`],
  [`Resize Proportionally`, `按比例调整大小`],
  [`Resize proportionally`, `按比例调整大小`],
  [`Resize to Fit`, `适应大小`],
  [`Resizing`, `调整大小`],
  [`Resolve`, `解决`],
  [`Resource use`, `资源使用情况`],
  [`Resources`, `资源`],
  [`Restart (R)`, `重新开始（R）`],
  [`Restore component`, `恢复组件母版`],
  [`Restore Component`, `恢复组件母版`],
  [`Restore default thumbnail`, `恢复默认封面`],
  [`Restore main component`, `恢复组件母版`],
  [`Restore this version`, `还原到这个版本`],
  [`Restore`, `恢复`],
  [`Restored main component`, `已恢复组件母版`],
  [`Restricting their role will limit their ability to edit or create files in this team.`, `限制他们的角色将限制他们在这个团队中编辑或创建文件的能力。`],
  [`Return to instance`, `返回实例`],
  [`Review our `, `查看我们的`],
  [`Review our Community guidelines`, `查看我们的社区指南`],
  [`Review team`, `确认团队`],
  [`Review`, `查看`],
  [`Revoke access`, `撤销访问`],
  [`Right padding`, `右边距`],
  [`right-click`, `右击`],
  [`Right-to-left Mirrored Forms`, `从右到左镜像形式`],
  [`Right`, `右侧`],
  [`Rotate 180˚`, `旋转 180°`],
  [`Rotate 90˚ left`, `向左旋转 90°`],
  [`Rotate 90˚ right`, `向右旋转 90°`],
  [`Rotation`, `旋转`],
  [`Round to pixel`, `对齐像素`],
  [`Round`, `圆头`],
  [`Rows`, `行`],
  [`Ruby notation forms`, `注音字符形式`],
  [`Rulers`, `标尺`],
  [`Run last plugin`, `运行最后一个插件`],
  [`Running your prototype`, `启动你的原型`],
  [`Saturation`, `饱和度`],
  [`Save 20%`, `节省 20%`],
  [`Save as .fig…`, `另存为 .fig 文件…`],
  [`Save local copy…`, `保存本地副本…`],
  [`Save photo`, `保存图片`],
  [`Save time and accelerate your workflow with beautifully designed templates`, `使用设计精美的模板节省时间，加快工作流程`],
  [`Save to version history…`, `保存至历史版本…`],
  [`Save`, `保存`],
  [`Saving…`, `保存中…`],
  [`Scale`, `缩放`],
  [`Scientific inferiors`, `科学下标符号`],
  [`Screen`, `滤色`],
  [`Scroll to`, `滚动到`],
  [`Scrolls`, `滚动`],
  [`Search commands…`, `搜索命令…`],
  [`Search the Figma Community`, `搜索 Figma 社区`],
  [`Search through all of Figma’s commands`, `搜索 Figma 的全部命令`],
  [`Search through menus, commands, and plugins`, `搜索菜单、命令和插件`],
  [`Search users`, `搜索用户`],
  [`Search…`, `搜索…`],
  [`Search`, `搜索`],
  [`seat/month`, `席位/月`],
  [`Security`, `安全`],
  [`See all`, `查看全部`],
  [`See edit access`, `查看编辑访问`],
  [`See edit permissions`, `查看编辑权限`],
  [`See how it works`, `看看 Figma 如何工作`],
  [`See in context`, `在设计稿中查看`],
  [`See more on Community `, `在社区查看更多内容 `],
  [`See what's being created in Figma`, `看看 Figma 里面正在创建什么`],
  [`Select a frame or object in a frame and use the circular node to drag a connection to another frame.`, `选择一个画框或一个画框中的对象，然后使用圆形节点将连接拖动到另一个画框。`],
  [`Select all with same effect`, `选择全部相同效果`],
  [`Select all with same fill`, `选择全部相同填充颜色`],
  [`Select all with same font`, `选择全部相同字体`],
  [`Select all with same instance`, `选择全部相同组件实例`],
  [`Select all with same properties`, `选择全部相同属性`],
  [`Select all with same stroke`, `选择全部相同描边`],
  [`Select all with same text properties`, `选择全部相同文本属性`],
  [`Select all`, `全选`],
  [`Select child`, `选择子元素`],
  [`Select children`, `选择子元素`],
  [`Select Component`, `选择组件`],
  [`Select conflicting variants`, `选择冲突的变体`],
  [`Select corrupted variants`, `选择损坏的变体`],
  [`Select inverse`, `反选`],
  [`Select layer menu`, `选择图层菜单`],
  [`Select layer`, `选择图层`],
  [`Select next sibling`, `选择下一个同级元素`],
  [`Select none`, `取消选择`],
  [`Select parent`, `选择父元素`],
  [`Select parents`, `选择父元素`],
  [`Select previous sibling`, `选择上一个同级元素`],
  [`Select the frame your prototype will begin with.`, `选择你原型起始的画框。`],
  [`Select which comment threads on this file you'll receive emails and notifications for.`, `选择这个文件中的哪些评论主题，你将收到电子邮件和通知。`],
  [`Selection colors`, `选择的颜色`],
  [`Selection`, `选择`],
  [`Send backward`, `下移一层`],
  [`Send Invite `, `发送邀请 `],
  [`Send invite`, `发送邀请`],
  [`Send Invite`, `发送邀请`],
  [`Send to back`, `移到底层`],
  [`Set as thumbnail`, `设为封面`],
  [`Set default properties`, `设置默认属性`],
  [`Set opacity to 10%`, `设置不透明度为 10%`],
  [`Set opacity to 100%`, `设置不透明度为 100%`],
  [`Set opacity to 50%`, `设置不透明度为 50%`],
  [`Set profile handle`, `设置个人主页账号`],
  [`Set team profile handle`, `设置团队主页账号`],
  [`Setting precise constraints lets you build fluid layouts to support multiple device sizes and breakpoints within the same group.`, `设置精确的约束条件可以让你构建流式布局，以支持同一组内的多种设备尺寸和断点。`],
  [`Settings`, `设置`],
  [`Shadow spread is not supported for vector type`, `矢量图层不支持阴影扩展`],
  [`Shadows`, `阴影`],
  [`Shape Tools`, `形状工具`],
  [`Shape`, `形状`],
  [`Share `, `分享 `],
  [`Share components and styles across your team by publishing them to the team library.`, `通过将组件和样式发布到团队组件库中，可以在你的团队中共享它们。`],
  [`Share components and styles across your team by publishing them to the Team Library.`, `通过将组件和样式发布到团队组件库中，在你的团队中共享它们。`],
  [`Share on Facebook`, `分享到 Facebook`],
  [`Share on Twitter`, `分享到 Twitter`],
  [`Share prototype`, `分享原型`],
  [`Share your projects with teammates, clients, and stakeholders but don’t let them mess up your files.`, `与队友、客户和利益相关者分享你的项目，但不要让他们弄乱你的文件。`],
  [`Share your thoughts using the comment box above.`, `使用上面的评论框分享你的想法。`],
  [`Share`, `分享`],
  [`Shared Projects`, `共享的项目`],
  [`Shared`, `已共享`],
  [`Sharing and Permissions`, `分享和权限`],
  [`Show as grid`, `显示为网格`],
  [`Show as list`, `显示为列表`],
  [`Show assets`, `显示资源`],
  [`Show autosave versions`, `显示自动保存的版本`],
  [`Show comments`, `显示评论`],
  [`Show dimensions on objects`, `在对象上显示尺寸`],
  [`Show dot grid`, `显示点状网格`],
  [`Show Full Version History`, `显示完整版本历史`],
  [`Show fun list emojis`, `显示趣味列表表情`],
  [`Show Google Fonts`, `显示谷歌字体`],
  [`Show hotspot hints on click`, `点击时显示热区提示`],
  [`Show in exports`, `在导出中显示`],
  [`Show in Files`, `在文件中显示`],
  [`Show in project`, `在项目中显示`],
  [`Show left sidebar`, `显示左侧边栏`],
  [`Show less`, `收起内容`],
  [`Show me what’s new`, `查看新功能`],
  [`Show me`, `定位`],
  [`Show more`, `查看更多`],
  [`Show notifications`, `显示通知`],
  [`Show only your comments`, `只显示你的评论`],
  [`Show presets and templates selector when creating new files`, `创建新文件时显示预设和模板选择器`],
  [`Show prototype settings`, `显示原型设置`],
  [`Show resolved comments`, `显示已解决的评论`],
  [`Show Resolved Comments`, `显示已解决的评论`],
  [`Show resolved`, `显示已解决的`],
  [`Show selection colors`, `显示所选项的颜色`],
  [`Show slices`, `显示切片`],
  [`Show this next time`, `下次继续显示`],
  [`Show toolbar and footer`, `显示工具条和页脚`],
  [`Show version history`, `查看版本历史`],
  [`Show/hide author`, `显示/隐藏作者`],
  [`Show/Hide selection`, `显示/隐藏所选项`],
  [`Show/Hide UI`, `显示/隐藏界面`],
  [`Show/Hide`, `显示/隐藏`],
  [`Show`, `显示`],
  [`Silver`, `银色`],
  [`Simple Kanban Template`, `简易看板模板`],
  [`Size`, `尺寸`],
  [`Skip for now`, `暂时跳过`],
  [`Slashed Zero`, `斜杠零`],
  [`Slice tool`, `切片工具`],
  [`Slice`, `切片`],
  [`Slide 16:9`, `幻灯片 16:9`],
  [`Slide 4:3`, `幻灯片 4:3`],
  [`Slide in`, `滑入`],
  [`Slide out`, `滑出`],
  [`Small caps`, `小型大写字母`],
  [`Small nudge`, `小微调`],
  [`Smart animate matching layers`, `智能动画匹配图层`],
  [`Smart animate`, `智能动画`],
  [`Smooth join selection`, `平滑连接所选项`],
  [`Snap to dot grid`, `对齐到点状网格`],
  [`Snap to geometry`, `对齐到形状`],
  [`Snap to objects`, `对齐到对象`],
  [`Snap to pixel grid disabled`, `已禁用对齐到像素`],
  [`Snap to pixel grid enabled`, `已启用对齐到像素`],
  [`Snap to pixel grid`, `对齐到像素`],
  [`Social media`, `社交媒体`],
  [`Soft light`, `柔光`],
  [`Solid`, `纯色`],
  [`Some variants are missing properties.`, `有些变体缺少属性。`],
  [`Some variants have the same property values applied. Change the values of these to resolve this.`, `有些变体应用了相同的属性值。修改这些变体的值来解决这个问题。`],
  [`Sort by`, `排序方式`],
  [`Space between`, `等距`],
  [`Space Grey`, `深空灰`],
  [`Space`, `空格`],
  [`Spacing between items`, `项目间距`],
  [`Spread`, `扩展`],
  [`Square`, `方头`],
  [`Stamp`, `印章`],
  [`Standard Ligatures`, `标准连字`],
  [`Star`, `星形`],
  [`Start ascending from`, `起始编号`],
  [`Start sequence from`, `起始编号`],
  [`Starter team`, `入门版团队`],
  [`Starter team overview`, `入门版团队概览`],
  [`Starter`, `入门版`],
  [`Starting frame`, `起始画框`],
  [`Status`, `状态`],
  [`Stay on topic`, `别跑题`],
  [`Stickers, icons, and reactions for your FigJam sessions`, `为你的 FigJam 会议提供贴纸、图标和互动内容`],
  [`Sticky note`, `便利贴`],
  [`Stretch Left and Right`, `左右拉伸`],
  [`Stretch Top and Bottom`, `上下拉伸`],
  [`Stretch`, `拉伸`],
  [`Strikethrough`, `删除线`],
  [`Stroke`, `描边`],
  [`Students and Educators`, `学生和教育工作者`],
  [`Style`, `样式`],
  [`Styles and Components`, `样式和组件`],
  [`Stylistic Alternates`, `文体替代字形`],
  [`Stylistic set 1`, `文体组合 1`],
  [`Stylistic set 10`, `文体组合 10`],
  [`Stylistic set 11`, `文体组合 11`],
  [`Stylistic set 12`, `文体组合 12`],
  [`Stylistic set 13`, `文体组合 13`],
  [`Stylistic set 14`, `文体组合 14`],
  [`Stylistic set 15`, `文体组合 15`],
  [`Stylistic set 16`, `文体组合 16`],
  [`Stylistic set 17`, `文体组合 17`],
  [`Stylistic set 18`, `文体组合 18`],
  [`Stylistic set 19`, `文体组合 19`],
  [`Stylistic set 2`, `文体组合 2`],
  [`Stylistic set 20`, `文体组合 20`],
  [`Stylistic set 3`, `文体组合 3`],
  [`Stylistic set 4`, `文体组合 4`],
  [`Stylistic set 5`, `文体组合 5`],
  [`Stylistic set 6`, `文体组合 6`],
  [`Stylistic set 7`, `文体组合 7`],
  [`Stylistic set 8`, `文体组合 8`],
  [`Stylistic set 9`, `文体组合 9`],
  [`Stylistic sets 1`, `文体组合 1`],
  [`Stylistic sets`, `文体组合`],
  [`Submit feedback`, `提交反馈`],
  [`Subscript`, `下标`],
  [`Subscription`, `订阅`],
  [`Substitute smart quotes`, `智能引号替换`],
  [`Subtract selection`, `减去顶层所选项`],
  [`Successfully published library updates`, `组件库更新发布成功`],
  [`Suffix`, `后缀`],
  [`Superscript`, `上标`],
  [`Support forum`, `支持论坛`],
  [`Support Forum`, `支持论坛`],
  [`Support:`, `技术支持：`],
  [`Support`, `支持`],
  [`Swap component instance`, `交换组件实例`],
  [`Swap fill and stroke`, `交换填充和描边`],
  [`Swap instance`, `交换实例`],
  [`Swap Instance`, `交换实例`],
  [`Swap overlay`, `交换叠加`],
  [`Swap with`, `交换到`],
  [`Switch account`, `切换帐户`],
  [`Table`, `表格`],
  [`Tablet`, `平板电脑`],
  [`Tags`, `标签`],
  [`Team building`, `团队建设`],
  [`Team icon updated`, `团队图标已更新`],
  [`Team libraries`, `团队组件库`],
  [`Team library is a Professional plan-only feature`, `团队组件库是专业版计划才有的功能`],
  [`Team library`, `团队组件库`],
  [`Team name`, `团队名称`],
  [`Team permissions: Admin`, `团队权限：管理员`],
  [`Team permissions: All`, `团队权限：全部`],
  [`Team permissions: Can edit`, `团队权限：可以编辑`],
  [`Team permissions: Can view`, `团队权限：可以查看`],
  [`Team permissions: No team permissions`, `团队权限：没有团队权限`],
  [`Team permissions: Owner`, `团队权限：创建者`],
  [`Team permissions`, `团队权限`],
  [`Team meetings`, `团队会议`],
  [`Team profile handle`, `团队主页账号`],
  [`Team project`, `团队项目`],
  [`Team Retrospective Template`, `团队回顾模板`],
  [`team settings`, `团队设置`],
  [`Team Templates`, `团队模板`],
  [`Teams`, `团队`],
  [`Temperature`, `白平衡`],
  [`Templates`, `模板`],
  [`Text align bottom`, `下对齐`],
  [`Text align center`, `水平居中`],
  [`Text align justified`, `两端对齐`],
  [`Text align left`, `左对齐`],
  [`Text align middle`, `垂直居中`],
  [`Text align right`, `右对齐`],
  [`Text align top`, `上对齐`],
  [`Text Styles`, `文本样式`],
  [`Text tool`, `文本工具`],
  [`Text`, `文本`],
  [`The current document has unsaved changes. Figma will continue trying to save in the background. Please try again later.`, `当前文档有未保存的更改。Figma 将在后台继续尝试保存。请稍后再试。`],
  [`The document has unsaved changes. Figma will continue to try auto-saving your work.`, `该文档有未保存的更改。Figma 将继续尝试自动保存你的工作。`],
  [`The document has unsaved changes. Reconnecting...`, `该文档有未保存的更改。正在重新连接…`],
  [`The file browser allows you to navigate through your account. You can use it to access personal files, create and join teams, and connect with the wider Figma community.`, `文件浏览器允许你在你的账户中进行浏览。你可以用它来访问个人文件，创建和加入团队，并与更广泛的 Figma 社区联系。`],
  [`The following apps have been given permission to access your Figma files on your behalf. If you see any apps you're not expecting here, remove their permissions below.`, `以下应用程序已被授予代表你访问 Figma 文件的权限。如果你在这里看到任何你不希望看到的应用程序，请在下面删除其权限。`],
  [`The following fonts are not available, and need to be replaced in order to edit text.`, `以下字体不可用，需要被替换才能编辑文本。`],
  [`The properties and values of these variants are conflicting.                 Change the applied values on these variants to resolve this.`, `这些变体的属性和值是冲突的。修改这些变体的应用值以解决这个问题。`],
  [`The properties and values of this variant are conflicting.                 Change the applied values on this variant to resolve this.`, `这个变体的属性和值是冲突的。修改这个变体的应用值以解决这个问题。`],
  [`The selected variant is missing one or more properties.`, `选中的变体缺少一个或多个属性。`],
  [`The selected variants are missing one or more properties.`, `选中的变体缺少一个或多个属性。`],
  [`Their recent projects will appear here.`, `他们最近的项目将出现在这里。`],
  [`There are more than 50 people working in this file right now, which can cause slowness. To keep things moving, we’ve temporarily turned off edit access and the ability to see other people’s cursors.`, `现在有超过50人在这个文件中工作，这可能会导致速度变慢。为了保证进度，我们已经暂时关闭了编辑权限和查看其他人鼠标指针的功能。`],
  [`There are no published styles in your drafts.`, `你的草稿中没有已发布的样式。`],
  [`They’ll update instantly no matter what network you’re on and with no need to connect via USB.`, `无论你在什么网络上，它们都会立即更新，而且无需通过 USB 连接。`],
  [`Thick`, `粗`],
  [`Thin`, `细`],
  [`This action will remove all of the components in this file from the library.`, `此操作将从组件库中删除该文件中的所有组件。`],
  [`This document contains unsaved changes. These changes are saved locally and will sync when Figma reconnects.`, `本文档包含未保存的更改。这些更改保存在本地，并将在 Figma 重新连接时同步。`],
  [`This file has unsaved changes.`, `当前文件有未保存的更改。`],
  [`This file's editor has disabled exporting, copying, and sharing.`, `这个文件的编辑器已经禁止导出、复制和分享。`],
  [`This file`, `当前文件`],
  [`This is a Figma Community profile.`, `这是 Figma 社区的个人主页。`],
  [`This is a Figma Community resource file.`, `这是一个 Figma 社区源文件。`],
  [`This is the Figma Community, `, `这是 Figma 社区，`],
  [`This is the Figma Community.`, `这是 Figma 社区。`],
  [`This is your team space. From here you can add collaborators, manage permissions, and see all of your projects owned by the team.`, `这是你的团队空间。在这里，你可以添加合作者，管理权限，并查看团队拥有的所有项目。`],
  [`This is your team's workspace. Create projects to help organize your files and invite members to your team to start collaborating. Click here to edit this description.`, `这是你的团队工作空间。创建项目来帮助组织你的文件，并邀请成员到你的团队来开始协作。点击这里来编辑这个简介。`],
  [`This person can still edit, because the file is set to allow editing by anybody with the link.`, `这个人仍然可以编辑，因为文件被设置为任何有链接的人都可以编辑。`],
  [`This project doesn't have any files.`, `这个项目没有任何文件。`],
  [`This team is for Education users only. New users will be required to verify their Education status.`, `这个团队只针对教育用户。新用户需要验证其教育状态。`],
  [`This week`, `本周`],
  [`Thumbnail set`, `已设为封面`],
  [`Thumbnail size: 1920x960 (1600x960 safe area)`, `封面尺寸：1920x960（1600x960 安全区域）`],
  [`Tidy up`, `整理`],
  [`Tile`, `平铺`],
  [`Tint`, `着色`],
  [`Title case`, `字首大写`],
  [`to add to version history while editing.`, `来添加到版本历史（编辑时）`],
  [`To confirm, please enter the name of the team.`, `确认删除，请输入团队名称。`],
  [`To create a component, select a layer and click the "Create component" button in the toolbar.`, `创建组件，请选择一个层，然后单击工具栏中的「创建组件」按钮。`],
  [`to create your own plugin and manage any plugins currently in development.`, ` 来创建你自己的插件，以及管理在开发中的插件`],
  [`to create and manage your own plugins.`, `创建和管理你自己的插件。`],
  [`To delete a connection, click and drag on either end.`, `要删除连接，请在任一端点单击并拖动。`],
  [`To edit this file, ask the file owner to share it with you with edit permissions.`, `要编辑这个文件，请文件所有者与你分享它的编辑权限。`],
  [`To pin a comment to a specific spot on the design, `, `要将评论钉在设计的特定位置上，`],
  [`To publish as a Team, move this file out of drafts and into a Team project.`, `如需以团队身份发布，请将此文件从草稿移动到团队项目中。`],
  [`To view your frames live on your device, just download Figma Mirror on your`, `要在你的设备上实时查看你的画框，只需在你的 `],
  [`Today`, `今天`],
  [`Tools`, `工具`],
  [`Top & Bottom`, `上 & 下`],
  [`Top and bottom`, `上下拉伸`],
  [`Top Center`, `顶部中间`],
  [`Top left corner radius`, `上左圆角半径`],
  [`Top Left`, `上左`],
  [`Top padding`, `上边距`],
  [`Top plugins`, `热门插件`],
  [`Top right corner radius`, `上右圆角半径`],
  [`Top Right`, `上右`],
  [`Top, right, bottom, and left padding can now be set independently.`, `现在可以独立设置顶部、右侧、底部和左侧的边距。`],
  [`Top`, `上`],
  [`Touch down`, `触摸按下`],
  [`Touch up`, `触摸离开`],
  [`Traditional Forms`, `传统形式`],
  [`Transform`, `变形`],
  [`Trending files`, `近期热门文件`],
  [`Trending`, `趋势`],
  [`Triangle Arrow`, `三角箭头`],
  [`Try Figma for free.`, `免费体验 Figma`],
  [`Try Figma for free`, `免费体验 Figma`],
  [`Try now`, `立即重试`],
  [`Turn into a list`, `转换成列表`],
  [`Type details`, `字体详情`],
  [`Type something to start searching...`, `输入点东西开始搜索…`],
  [`Type`, `类型`],
  [`Typography`, `字体排印`],
  [`Uh oh... we can't open that file`, `抱歉… 我们打不开那个文件`],
  [`UI Design`, `UI 设计`],
  [`UI Kits`, `素材库`],
  [`UI kits`, `素材库`],
  [`Unable to follow this profile: You're already following this user`, `无法关注这个个人主页：你已经关注这个用户了`],
  [`Unable to install plugin. Please try again.`, `无法安装插件，请重试。`],
  [`Unable to leave document`, `无法离开文档`],
  [`Unable to like this file: You already liked this file.`, `无法点赞这个文件：你已经点赞过这个文件了~`],
  [`Underline`, `下划线`],
  [`Undo`, `撤销`],
  [`Unfollow`, `取消关注`],
  [`Ungroup selection`, `取消编组所选项`],
  [`Ungroup`, `取消编组`],
  [`Uninstall`, `卸载`],
  [`Uninstalled`, `已卸载`],
  [`Union selection`, `连集所选项`],
  [`Unique handle`, `唯一账号`],
  [`Unliked`, `已取消点赞`],
  [`Unlimited cloud storage`, `无限制的云存储`],
  [`Unlimited FigJam files (during beta)`, `无限的 FigJam 文件（内测期间）`],
  [`Unlimited version history is available to paid teams.`, `付费的团队可以使用无限的历史版本`],
  [`Unlimited`, `无限制`],
  [`Unlink from styles to customize mixed contents.`, `取消链接样式，可自定义多个内容。`],
  [`Unpublish`, `取消发布`],
  [`Unsupported file format`, `不支持的文件格式`],
  [`Up to 15 characters (letters, numbers, or _)`, `最多 15 个字符（字母、数字或 _）`],
  [`Up to 2 editors`, `最多 2 个编辑者`],
  [`Update all`, `全部更新`],
  [`Update`, `更新`],
  [`Updates to components or styles`, `组件或样式的更新`],
  [`Updates`, `更新`],
  [`Upgrade Figma plan`, `升级 Figma 计划`],
  [`Upgrade now`, `马上升级`],
  [`Upgrade plan`, `升级计划`],
  [`Upgrade team`, `升级团队`],
  [`Upgrade this team to publish components to the Team Library and use them across all files.`, `升级团队，就可以将组件发布到团队组件库，且跨文件使用。`],
  [`Upgrade to collaborate and share design libraries with your entire team.`, `升级以与你的团队进行协作并共享设计组件库。`],
  [`Upgrade to collaborate with more teammates`, `升级后可与更多队友合作`],
  [`Upgrade to Organization`, `升级到组织版`],
  [`Upgrade to Professional`, `升级到专业版`],
  [`Upgrade to the Professional plan or to an Organization and get access to shared team libraries, advanced security features and`, `升级到专业版计划或组织版，可以使用共享的团队组件库、高级安全功能以及`],
  [`Upgrade your plan to collaborate with more people and better organize your design files.`, `升级你的计划后可以和更多人合作，更好的管理你的设计文件`],
  [`Upgrade your plan to take full advantage of Figma.`, `升级你的计划以充分利用 Figma 的优势。`],
  [`Upgrade your plan`, `升级你的计划`],
  [`Upgrade your team`, `升级你的团队`],
  [`Upgrade`, `升级`],
  [`Upgraded:`, `升级时间：`],
  [`Upper case`, `大写`],
  [`Uppercase`, `大写`],
  [`US$12 per editor/month`, `每个编辑者 12 美元/月`],
  [`Use as mask`, `设为蒙版`],
  [`Use Cases`, `使用案例`],
  [`Use Developer VM`, `使用开发者虚拟机`],
  [`Use libraries for quick access to components from other files.`, `使用库可以快速访问其他文件中的组件。`],
  [`Use number keys for opacity`, `使用数字控制透明度`],
  [`Use profile`, `使用个人主页`],
  [`Use shape outlines`, `使用形状轮廓`],
  [`Use style`, `使用样式`],
  [`Use template`, `使用模板`],
  [`Use the circular node to connect the selected object to another frame.`, `使用圆形节点将选定的对象连接到另一个画框。`],
  [`Use the play button in the toolbar to play your prototype. If there are no connections, the play button can be used to play a presentation of your frames.`, `使用工具栏中的演示按钮演示原型。 如果没有连接，“演示”按钮将演示你的画框用于演示。`],
  [`Used in this file`, `本文件中使用`],
  [`UX Design`, `UX 设计`],
  [`Variants`, `变体`],
  [`Vector networks`, `矢量网络`],
  [`Vector`, `矢量`],
  [`Version `, `版本 `],
  [`Version History `, `版本历史 `],
  [`Version History`, `版本历史`],
  [`Version history`, `版本历史`],
  [`versions`, `版本`],
  [`Vertical alternates and rotation`, `竖排替代字形和旋转`],
  [`Vertical alternates`, `竖排替代字形`],
  [`Vertical direction`, `垂直方向`],
  [`Vertical Padding`, `垂直间距`],
  [`Vertical scrolling`, `垂直滚动`],
  [`Vertical`, `垂直`],
  [`Video tutorials`, `视频教程`],
  [`View Community page`, `查看社区页面`],
  [`View Community Profile`, `查看社区个人主页`],
  [`View Community profile`, `查看社区个人主页`],
  [`View only`, `仅查看`],
  [`View page`, `查看页面`],
  [`View Profile`, `查看个人主页`],
  [`View upgrade reason`, `查看升级原因`],
  [`View`, `查看`],
  [`Viewer permission changed`, `查看者权限已修改`],
  [`Want to edit this file with others?`, `想跟别人一起编辑这个文件吗？`],
  [`Want to edit this file?`, `想编辑这个文件吗？`],
  [`Watch`, `手表`],
  [`We designed them to keep Community awesome for our beloved creators and commenters.`, `我们设计它们是为了让社区对于我们心爱的创作者和评论者来说非常优秀。`],
  [`We’re different from other design tools in some really special ways, so we’d like to take you through them.`, `我们和其他设计工具有一些非常特别的地方，所以我们想带你了解一下。`],
  [`Web Design`, `网页设计`],
  [`Web design`, `网页设计`],
  [`Weight`, `字重`],
  [`Welcome to Figma Community!`, `欢迎来到 Figma 社区！`],
  [`Welcome to Figma!`, `欢迎来到 Figma！`],
  [`Welcome, new commenter!`, `欢迎你，新来的评论员！`],
  [`What’s New`, `新功能`],
  [`When leaving comments on Community resources, we ask that you…`, `在社区资源上评论时，我们要求你…`],
  [`While clicking…`, `点击时…`],
  [`While dragging from assets…`, `从资源面板拖动时…`],
  [`While dragging to select…`, `拖动并选中时…`],
  [`While editing a shape…`, `编辑形状时…`],
  [`While hovering`, `当悬停时`],
  [`While moving…`, `移动时…`],
  [`While pointing…`, `指向时…`],
  [`While pressing`, `当按下时`],
  [`While resizing…`, `调整大小时…`],
  [`Whiteboards and Stickies`, `白板和贴纸`],
  [`who counts as an editor?`, `谁会被算做编辑者？`],
  [`Width – Scale down to fit width`, `宽度 - 缩小以适应宽度`],
  [`Width`, `宽`],
  [`will show up here as they become available.`, `可用时将显示在这里。`],
  [`Wireframes`, `线框图`],
  [`Wireframing`, `线框图`],
  [`Writing direction`, `书写方向`],
  [`Writing Direction`, `书写方向`],
  [`X-Offset`, `X 轴偏移`],
  [`Y-Offset`, `Y 轴偏移`],
  [`yesterday`, `昨天`],
  [`You are a verified Education user!`, `你已经认证为教育版用户！`],
  [`You are currently the owner of `, `你目前是”`],
  [`You can always change this in Preferences.`, `你一直都可以在偏好设置中修改这个设置。`],
  [`You can favorite a project and it will be pinned under the team in the left sidebar.`, `你可以收藏一个项目，它就会固定在左侧边栏的团队下面。`],
  [`You can head there by clicking on `, `你可以通过点击 `],
  [`You can now edit files in any Education Team.`, `你可以在任何一个教育版团队编辑文件。`],
  [`You can update user permissions on the team page after setting up.`, `设置好后可以在团队页面更新用户权限。`],
  [`You can't undo this action.`, `此操作不可撤销。`],
  [`You don't have any connected apps`, `你没有任何已连接的应用`],
  [`You don't have any deleted files.`, `没有被删除的文件。`],
  [`You don't have any notifications.`, `暂无消息通知。`],
  [`You don't have any plugins installed`, `没有已安装的插件`],
  [`You don't have permission to remove files from this project.`, `你没有权限从这个项目中移除这个文件。`],
  [`You haven't published any plugins yet`, `你还没有发布任何插件`],
  [`You will permanently lose all access to the projects and files in this team, and you cannot undo this action.`, `你将永久失去对该团队中的项目和文件的所有访问权限，并且你无法撤销此操作。`],
  [`You`, `你`],
  [`You'll need the`, `你需要`],
  [`Your comments`, `你的评论`],
  [`Your description was updated`, `你的简介已更新`],
  [`Your file will soon be available for everyone in the Community to duplicate, remix, and share. Thanks for your contribution. You rock.`, `你的文件很快就会被社区中的每个人复制、重新演绎和分享。感谢你的贡献。你是最棒的。`],
  [`Your Instagram URL was updated`, `你的 Instagram 地址已更新`],
  [`Your kudos and feedback are welcome!`, `欢迎你的点赞和反馈!`],
  [`Your location was updated`, `你的位置已更新`],
  [`Your new Community profile is live. View your profile to customize it. Everyone can now find you at:`, `你的社区个人主页已经生效。查看你的个人主页来自定义。所有人都能通过以下链接找到你：`],
  [`Your offline changes were synced`, `你的离线更改已同步`],
  [`Your primary email is used for all Community notifications.`, `你的首选邮箱用于所有社区通知。`],
  [`Your profile is visible to the public at`, `大家可以在这里看到你的个人主页`],
  [`Your recent projects will appear here.`, `你最近的项目会出现在这里。`],
  [`Your teams and favorited projects will appear here`, `你的团队和收藏的项目将出现在这里`],
  [`Your Twitter URL was updated`, `你的 Twitter 地址已更新`],
  [`Your Website URL was updated`, `你的网站地址已更新`],
  [`YouTube videos`, `YouTube 视频`],
  [`Zoom In`, `放大`],
  [`Zoom in`, `放大`],
  [`Zoom Out`, `缩小`],
  [`Zoom out`, `缩小`],
  [`Zoom to 100%`, `缩放至 100%`],
  [`Zoom to 200%`, `缩放至 200%`],
  [`Zoom to 50%`, `缩放至 50%`],
  [`Zoom to fit`, `缩放以适应大小`],
  [`Zoom to next frame`, `缩放至下一个画框`],
  [`Zoom to previous frame`, `缩放至上一个画框`],
  [`Zoom to selection`, `缩放至选中范围`],
  [`Zoom/view Options`, `缩放/视图选项`],
  [`Zoom`, `缩放`],
]


let MutationObserver = window.MutationObserver || window.WebKitMutationObserver;
let MutationObserverConfig = {
  childList: true,
  subtree: true,
  attributeFilter: ['data-label'],
  characterData: true
};

let observer = new MutationObserver(function (mutations) {
  let treeWalker = document.createTreeWalker(
    document.body,
    NodeFilter.SHOW_ALL,
    { 
        acceptNode: function (node) {
            if(node.nodeType === 3 || node.hasAttribute('data-label')) {
                return NodeFilter.FILTER_ACCEPT;
            }else {
                return NodeFilter.FILTER_SKIP;
            }
        } 
    },
    false
  );
  let dataMap = new Map();
  allData.forEach(([key, val]) => {
    if (key && !dataMap.has(key)) {
      dataMap.set(key, val);
    }
  });
  let currentNode = treeWalker.currentNode;
  while (currentNode) {
    if(currentNode.nodeType === 3) {
        let key1 = currentNode.textContent;
        if (dataMap.has(key1)) currentNode.textContent = dataMap.get(key1);
    }else {
        let key2 = currentNode.getAttribute('data-label');
        if (dataMap.has(key2)) currentNode.setAttribute('data-label', dataMap.get(key2));
    }

    currentNode = treeWalker.nextNode();
  }
});

observer.observe(document.body, MutationObserverConfig);
